### ISSUE TITLE
[DEHYDRATED] missing dependency

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#11]
The package needs '**diff**' if we want do a dns-01 challange.

Please add this dependency to the the package. Thanx

**Comment by fda77** [comment]
Thx, fixed: https://github.com/Freetz-NG/freetz-ng/commit/ca1695bef23124dc303daf6cd499a38a36bd2b62


Automatic refrerences do not work, as i use another repo which pushes to this repo.
But automatic issue closing seems to work...
