### ISSUE TITLE
7590 7.21: mc ncursesw UTF-8

### ISSUE THREAD

**Issue by forenuser** [Freetz-NG/freetz-ng#114]
Mit ncursesw werden bei mc nun wieder Buchstaben anstatt der Rahmen dargestellt. Wenn ich mit der Maus klicke, werden irgendwelche Zeichen in der Kommandozeile eingefügt, anstatt die geklickte Aktion auszuführen. Die .config Datei kann ich bei Bedarf hochladen.

**Comment by fda77** [comment]
Vermutlich passt die Einstellung deines Terminalclients nicht

**Comment by forenuser** [comment]
Ist die gleiche Einstellung von Putty. Wenn ich slang wähle und ein Image baue wird mc mit der gleichen Einstellung korrekt dargestellt.

**Comment by fda77** [comment]
Wenn du mit einem Franzosen, Deutschen und Polen sprichst, meinst du jeder versteht dich, nur weil du immer den gleichen Mund verwendest?

**Comment by forenuser** [comment]
Im alten Issue hatte ich geschrieben, dass MC sowohl mit slang, als auch mit ncursesw funktioniert. Dabei hatte ich die gleiche putty Einstellung verwendet. Nach der letzten Änderung funktioniert das nun nicht mehr. OK, dann muss ich halt für MC nun explizit slang verwenden.

**Comment by fda77** [comment]
Das wäre dann das einfachste

**Comment by feedzapper** [comment]
> Mit ncursesw werden bei mc nun wieder Buchstaben anstatt der Rahmen dargestellt. Wenn ich mit der Maus klicke, werden irgendwelche Zeichen in der Kommandozeile eingefügt, anstatt die geklickte Aktion auszuführen. Die .config Datei kann ich bei Bedarf hochladen.

putty -> Window -> Translation -> Enable VT100 line drawing even in UTF-8 Mode

**Comment by forenuser** [comment]
Die Line Drawings gehen mit dieser Einstellung. Bei mir stand Terminal-Type auf "xterm". Das habe ich auch angepasst. Bekommst Du auch cryptische Zeichen in der Kommandozeile unten, wenn Du mit der linken Maus Taste ins Fenster klickst oder kannst Du MC mit der Maus bedienen?

**Comment by feedzapper** [comment]
Yep, Maus geht bei mir auch nicht - es kommen irgendwelche ESC sequenzen. 
Evtl. muss man noch was beim Compilieren von dem MC Package dafür berücksichtigen ?
auch start mit "mc -x" ergibts das selbe Ergebnis ..

**Comment by forenuser** [comment]
Ich habe da was gefunden. Das sollte eigentlich in unserer Version schon gelöst sein: [https://midnight-commander.org/ticket/3954](url)

**Comment by fda77** [comment]
Solche Dinge könnte man hier hinterlegen:
 - im Repo: https://github.com/Freetz-NG/freetz-ng/blob/master/docs/make/mc.md
 - Ausgabe: https://freetz-ng.github.io/freetz-ng/make/mc

**Comment by feedzapper** [comment]
Yep nun gehts.
In Putty kann man dann auch noch justieren - wie mit der Maus bei drag und drop verfahren werden soll.
-> Selections -> options controlling copy an paste 
wenn man mal lange weile hat ;-)

**Comment by feedzapper** [comment]
nano sollte auch mit der Maus funktionieren.
Es ist aber in der nano.mk explizit deaktiviert (--disable-mouse). Dabei laufen alle Versuche zur späteren Aktivierung über die nanorc mit "set mouse" oder beim Start von nano über "nano -m" im Shell der Box ins leere ...

**Comment by fda77** [comment]
Aktiviert es wenn ihr es braucht. Falls die Binary dadurch viel größer wird oder eine zusätzliche Libs benötigt wird sollte es eine eigene Option sein. 
Da das ursprüngliche Problem keines ist...

**Comment by forenuser** [comment]
Bei nano funktioniert bei mir Copy und Paste mit der Maus. Welche Aktionen kann man sonst noch ausführen? Ohne dem Menü am  unteren Rand kann ich nano jedoch nicht bedienen, da ich die Ctrl Tastenkombinationen nicht auswendig kann.

**Comment by forenuser** [comment]
--disable-mouse scheint nur die folgende Funktion abzuschalten:

Nano has its own built-in mouse services, but they are limited. They provide only the ability to move the cursor to the point where you click, and to mark the beginning and end of a section of text. Use the Alt-M key combination to toggle between using the terminal's mouse services and nano's built-in mouse services.

Viel mehr, als den Cursor an eine bestimmte Position zu setzen, kann man scheinbar nicht machen. Für Copy und Paste muss man wieder in den Terminal Modus gehen, der auch ohne Aktivierung der Nano internen Mouse Services funktionieren sollte.
