### ISSUE TITLE
WLAN im IP-Client-Modus

### ISSUE THREAD

**Issue by bmaehr** [Freetz-NG/freetz-ng#123]
Hallo,

Ich bin schon seit Stunden auf der Suche nach einer Möglichkeit die Fritzbox als WLAN Router mit einem beliebigen WLAN-Netzwerk (also nicht als Repeater mit einem AVM Access Point sondern dem WLAN einer "Fremdfirma" als Verbindung zum Internet) zu betreiben. 
Da das über die AVM Oberfläche von AVM deaktiviert wurde, Netzwerke die nicht von AVM sind zu repeaten, hab ich gehofft, dass es zumindest ein freetz package gibt, das diese Möglichkeit eröffnet, auch wenn die Konfiguration evt nicht schön über die Oberfläche möglich ist.

Ich hab jedoch nichts gefunden und bin erstaunt, da es meiner Ansicht nach doch eine häufige Anforderung ist und nach meinem Verständnis mit Linux auch nicht allzuschwer zu implementieren sein sollte. Oder übersehe ich was?

**Comment by fda77** [comment]
Ja, mehreres:
 - Dies ist keine Forum sondern ein Bugtracker
 - Die Option selbst im AVM Webinterface

**Comment by bmaehr** [comment]
Es war als Feature Request gedacht.

Nach vielen Stunden Suche in unzähligen Diskussionsforen, in denen ich Hinweise auf diese Funktion gefunden habe, konnte ich das Problem beheben: Durch die Installation der ungefreezten AVM Version. Es ist also schlussendlich ein Bug in freetz.

**Comment by berndy2001** [comment]
Fehlt ein Eintrag in der Webconfig oder wie kann man sich das vorstellen?

**Comment by fda77** [comment]
Nö, Anwenderfehler. Bei mir gehts nämlich, auch mit Freetz

**Comment by bmaehr** [comment]
So
![image](https://user-images.githubusercontent.com/16438498/101298471-6b03e300-382e-11eb-9902-224b76a05b67.png)

**Comment by berndy2001** [comment]
Hab bei mir nochmals geschaut, hier sieht alles wie gewohnt aus.
Hast du schon probiert einen frischen Checkout mit Minimal-Image zu erstellen?

**Comment by Conan179** [comment]
@bmaehr ferräst du auch mal WELCHE fritzbox du hast?

**Comment by bmaehr** [comment]
"ferräst" ... Augenkrebs
Fritzbox 7390 (Ja, als mir klar geworden ist, dass mir da ein Feature fehlt, hätte ich daran denken sollen es dazu zu schreiben)

**Comment by Conan179** [comment]
> ... Augenkrebs
Nennt sich LRS, ich bin raus, dumm anmachen lasse ich mich nicht.

**Comment by bmaehr** [comment]
Es war nicht böse gemeint, nur schüttelt es mich, wenn ich sowas sehe ....
