### ISSUE TITLE
[build] false negatives in log during build

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#13]
There is a false negatives message during build.
![warning](https://user-images.githubusercontent.com/14336586/76133213-66986880-6017-11ea-9e4c-7780da414e62.png)

**Comment by fda77** [comment]
Annoying that github does not link the commit which closed this issue.
So: https://github.com/Freetz-NG/freetz-ng/commit/33565c8d5a12ec6ee364b2a139a19fe1a1893085
