### ISSUE TITLE
[dehydrated] please add missing upstream patch

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#14]
There is a missing [hotfix](https://github.com/dehydrated-io/dehydrated/commit/946e5712ba86b15afb4cf908eb7d0785c87195b8) for the package dehydrated.
Please add the [patch](https://github.com/Freetz-NG/freetz-ng/files/4301221/fixed_small_logic_bug.zip).
.

**Comment by fda77** [comment]
Fixed: https://github.com/Freetz-NG/freetz-ng/commit/cd84bd9fdd847c34e88a8a0094802304c1f0cef0
You noticed dehydrated seems to be dead? 
 - https://github.com/dehydrated-io/dehydrated/commit/dfffb1b88bbb452b0a0e77b80ce7d6df91ea984f
 - https://lukas.im/2020/01/30/selling-dehydrated/index.html
