### ISSUE TITLE
Error Anzeige bei Kernelversion

### ISSUE THREAD

**Issue by muckel-sassi** [Freetz-NG/freetz-ng#144]
Hallo,
ich habe eben ein aktuelles Image für die 7490 7.21 gebaut, was soweit auch funktioniert hat. Was mir aber aufgefallen ist, ist, dass unter Mod-Info -> Kernelversion ein Fehler (mit) angezeigt wird

Kernelversion3.10.107 (jenkins@edxbuildxjplxpsq19p1xvr9xavmdect) (collect2: error: ld returned 1 exit status)

Ist das "nur" ein optischer Fehler, oder leigt da was im Argen?

**Comment by fda77** [comment]
Wenn man einen eigenen (replace) Kernel hat, steht in der 2. klammer der Compiler: `(gcc version 5.5.0 (GCC) ) `
Beim original Kernel hat das beim Compilieren (bei AVM ) wohl nicht geklappt
```
$ cat /proc/version
Linux version 3.10.107 (jenkins@edxbuildxjplxpsq19p1xvr9xavmdect) (collect2: error: ld returned 1 exit status) #1 SMP Mon Aug 17 17:21:20 CEST 2020
```
Also nur "unschön"
