### ISSUE TITLE
[External] Illegal instruction

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#147]
Hi,

sometimes 'external' will be normal executed and sometimes i get this error message:

/var/log/external.log
Starting external (/var/media/ftp/uStor01/external):
Waiting for mod-startup: .... done.
Waiting for time-synchronisation: ............................. done.
Illegal instruction
Starting external finished.

/var/log/mod_mount.log
[INFO] /dev/sda1 - mounted as /var/media/ftp/FREETZ (ext4)

Can it be that the folder is not mounted at this point (this happens since async changes)?

**Comment by fda77** [comment]
External starts after a devices is mounted, udevmount hooks into avm methods and starts it.
There is a very new logfile which is not accessible by webif. It contains all messages from boot with timestamps: `cat /var/log/freetz.log`
Which Packages should be started? Have you a `/tmp/flash/mod/rc.external` file?

With my 7490 i have also a problem with a very old usb-stick: Sometimes it is not detected on system start, a "reboot" fixes it

**Comment by harryboo** [comment]
Hi, close this ticket. After a reboot everything works.

**Comment by fda77** [comment]
You are using the DEB oscam addon??

**Comment by harryboo** [comment]
No, only freetz-ng...
