### ISSUE TITLE
Passwortänderung killt Webinterface auf :81 bei FritzOS-Version v7.21 / Fritzbox 7490

### ISSUE THREAD

**Issue by gauner1986** [Freetz-NG/freetz-ng#153]
Hi,
mit folgenden Einstellungen habe ich aktuell das Problem, dass eine Änderung des Initialpassworts das Webinterface auf Port 81 killt. (Connection Refused):

Level of Competence: expert, Hardware: 7490 eingestellt, Firmware 7.21 eingestellt.

Danach habe ich das Image mit diesen Basic-Einstellungen gebaut und mit push_firmware geflashed.

Wenn man bspw. die authorized_keys für SSH bearbeiten möchte, werden die Änderungen durch das Webinterface nicht gespeichert. Es erscheint wieder die sample-config nach einem Klick auf Speichern.

Hier hat jemand dasselbe Problem:

https://www.ip-phone-forum.de/threads/freetz-ng-restart-from-scratch-fail-for-3490-und-7580.309046

**Comment by fda77** [comment]
Ich vermute eine Änderung in der Busybox die bislang nicht aufgefallen ist
