### ISSUE TITLE
Build Umgebung für freetz-ng

### ISSUE THREAD

**Issue by janfreetz** [Freetz-NG/freetz-ng#155]
Hallo Developer,
wo finde ich ein Virtualbox VDI Datei für die Standard Build Umgebung?
Oder wie erstelle ich mir eine default Build Umgebung, damit ich / wir auf gleichem Stand sind?
Die soll für 154.07.21 rev82154 {ALL} [PSQ19] sein.
https://osp.avm.de/fritzbox/fritzbox-7590/
source-files-FRITZ.Box_7590-07.21.tar.gz   
VG
Jan

**Comment by fda77** [comment]
Hallo Benutzer, jedes halbwegs aktuelle Linux sollte passen. Mindestens diese Pakete werden benötigt: https://freetz-ng.github.io/freetz-ng/wiki/10_Beginner/install.de.html#installation-der-ben%C3%B6tigten-pakete-ubuntu
Oder wie viele eine fertige VM von Gismotro benutzen, siehe readme unten auf https://github.com/Freetz-NG/freetz-ng

**Comment by fda77** [comment]
Es gibt übrigens oben das "Discussions", "Issues" sind für Fehler

**Comment by janfreetz** [comment]
Ok, sorry. 
Wo sollte man allgemeine Fragen stellen?

**Comment by fda77** [comment]
Wie gesagt, zu "Discussions", das ist eine neue Funktion von Github.
Q&A steht für Fragen&Antworten

**Comment by janfreetz** [comment]
Viel Erfolg beim Neubeginn.

**Comment by fda77** [comment]
Das ist ne Kategorie in den Diskussionen

**Comment by PeterPawn** [comment]
Wenn das Problem (https://github.com/github/feedback/discussions/2952) gefixt wurde, kann man auch wieder Issues in Discussions umwandeln - das hält die "Fehlerliste" klein und übersichtlich (was auch bei "closed" das Ziel sein sollte, damit andere bei der Suche nicht über zu viele falsch zugeordnete Themen iterieren müssen).

**Comment by fda77** [comment]
Prima dass das bald kommt. Ich hatte das hinter "Transfer" erwartet, aber das wird man wohl nicht so oft (nie) brauchen
