### ISSUE TITLE
ssh_authorized_keys werden über WebIf (Port 81) nicht gespeichert

### ISSUE THREAD

**Issue by gauner1986** [Freetz-NG/freetz-ng#156]
Der Button "Übernehmen" nimmt die Änderungen zwar entgegen, sie werden aber nicht übernommen (7490_07.21.all_freetz-ng-17674-0bc169437_20210112-143011.image). Der Inhalt der Konfiguration ist nach dem Reload derselbe.

**Comment by gauner1986** [comment]
Scheint mein Fehler gewesen zu sein. Ich hatte vergessen oberhalb des Keys den Benutzer zu spezifizieren. Hier könnte eine Fehlermeldung helfen. :)

**Comment by fda77** [comment]
Prima :)
Falls du eine Meldung einbauen willst, eine dieser Dateien sollte die passende sein: https://github.com/Freetz-NG/freetz-ng/tree/master/make/authorized-keys/files/root/usr/bin
