### ISSUE TITLE
jpegsrc.v9c.tar.gz MD5 checksum has changed

### ISSUE THREAD

**Issue by pkgzm** [Freetz-NG/freetz-ng#157]
The build stops after downloading because of a checksum error verification:

Download succeeded - "http://ijg.org/files/jpegsrc.v9c.tar.gz"  ->  saved to folder "dl"
Checksum mismatch for dl/jpegsrc.v9c.tar.gz: MD5:=cbc68018646e09b3fd8091e3de5ea451 (expected: 93c62597eeef81a84d988bccbda1e990)

**Comment by fda77** [comment]
Da wurden heimlich ungültige Zeichen in einer Datei entfernt
