### ISSUE TITLE
config load not possible

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#18]
After a clean checkout there is no load and save button for config files.
![load_not_possible](https://user-images.githubusercontent.com/14336586/82244277-4e12cb80-9941-11ea-82e5-0cab2ab0af3c.png)

**Comment by fda77** [comment]
I deleted them here: https://github.com/freetz-ng/freetz-ng/commit/49df5bac9
 * i never used  them by myself
 * there are users which save under a random name and expect that ```make```knows it
As you are the 2nd complaining, i'll revert it

**Comment by fda77** [comment]
Run ```make kconfig-dirclean```after pull to apply patches!
