### ISSUE TITLE
[make] distclean doesnt work

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#19]
the command 'make distclean' does nothing....

normally all files and folders used to create an image except the content of the dl folder will be deleted.
![distclean_doesntwork](https://user-images.githubusercontent.com/14336586/82760096-b1917300-9df1-11ea-9ddb-eab86280e42c.png)

**Comment by fda77** [comment]
try "distclean"

**Comment by harryboo** [comment]
Sorry,
