### ISSUE TITLE
[remove patch] only a warning at 'remove webdav'

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#20]
There is a warning if the patch 'remove webdav' is selected.

attached a log from the creation of a 7390 image:
![7390_remove_webdav_warning](https://user-images.githubusercontent.com/14336586/82760206-58760f00-9df2-11ea-95d0-c5de297eca0b.png)

**Comment by fda77** [comment]
Before https://github.com/Freetz-NG/freetz-ng/commit/a6b39568401cceecc66526faaef043abe1829815
these "warnings" (not errors) where only visible with verbose 3.
But verbose 3 never really worked for "build", only the "script" part.
For eg "configure" verbose above 2 was ignored, and nothing was displayed, like verbose 0.
So nothing to worry, lower verbose does not show the warnings

**Comment by fda77** [comment]
Messages are shown with verbos=2 only, should be okay
