### ISSUE TITLE
Error when make or make menuconfig

### ISSUE THREAD

**Issue by JohnPaden** [Freetz-NG/freetz-ng#205]
make menuconfig throws 
ERROR: The library libz.so (32-bit) was not found in /etc/ld.so.cache.
Basis is freetz linux with up to date apt-get upgrade.
the file libz.so does exist in various places, but not in /etc/ld.se.cache.

Any hint?

**Comment by berndy2001** [comment]
Have a look at https://freetz-ng.github.io/freetz-ng/NEWS.html#2021-02-17 and #203
