### ISSUE TITLE
Anfrage wegen REETZ_IMAGE_NAME_PREFIX

### ISSUE THREAD

**Issue by freetz-ng-mod** [Freetz-NG/freetz-ng#211]
Hi fda,

ich habe mal eine frage. Gibt es eine Möglichkeit FREETZ_IMAGE_NAME_PREFIX an eine andere position zu setzen als ganz vorne. ZB. Vor .image

**Comment by fda77** [comment]
Dann wäre es doch kein PRÄfix mehr! https://de.wikipedia.org/wiki/Pr%C3%A4fix

**Comment by freetz-ng-mod** [comment]
OK !!!!

Danke für den guten WiKI link.

Ich wusste was es heißt. Gibt es eine Chance in freetz-ng ein end name zu bekommen. Da es hier nicht um den Namen geht sondern mehr um Infos was in freetz drin ist

**Comment by fda77** [comment]
Wenn man eine neue Option erstellt muss man der schon einen Namen geben. Was schlägst du denn vor? Endfix find ich nicht so gut. Idefix hat auch schon ne andere Bedeutung
Da das ganze aber ne triviale Angelegenheit ist könntest du doch einen Patch/Pullrequest machen
