### ISSUE TITLE
Selecting "USB root 0.2" crashes menuconfig

### ISSUE THREAD

**Issue by thiloms** [Freetz-NG/freetz-ng#22]
Hi,

**How to reproduce the error:**
1. Clone a fresh freetz-ng and run "make menuconfig"
2. Select "Packages->Unstable->USB root 0.2"
3. Try to exit Submenu "unstable" and the menu will crash

I used USB root previously with my 7390 without any issue. Now I have a 7590 and wanted to use it also.
I don't figure it out why the menu crashes but I guess it has something todo with the replace kernel feature, with is currently not available for the 7590.

**Comment by fda77** [comment]
The error is only visible a short period of time:
```
ERROR: unmet direct dependencies detected for FREETZ_PACKAGE_E2FSPROGS
  Depends on [n]: FREETZ_REMOVE_AVM_E2FSPROGS [=n]
  Selected by [y]:
  - FREETZ_PACKAGE_USBROOT_E2FSCK [=y] && FREETZ_PACKAGE_USBROOT [=y]
```
