### ISSUE TITLE
Wie komme ich an ein Crashlog ran?

### ISSUE THREAD

**Issue by Conan179** [Freetz-NG/freetz-ng#262]
Hi, ich hab heute abend ein neues Image gebaut, meine änderungen waren, ein git pull und hab das vsftp endfernt.
Jetzt Startet meine 6590 alle paar minuten neu.
Damit ich rausfinden kann warum sie das macht, ist meine frage wie komme ich an einen crashlog ran?
Das Image wo immer wieder neustartet ist:
FritzOS 07.25 rev87194 (22.03.2021 13:55:32)
Freetz ng-18229M-eca6d622b (09.04.2021 21:29:39)

Im punkt "AVM-logs" habe ich noch "hdl=18 aha           triggered before: 130.520 s(avg   0.000 s) maybe crashed" gefunden, bevor sie neugestartet ist.

**Comment by fda77** [comment]
Die Crash-Logs von AVM sollten auch noch nach einem Neustart vorhanden sein, falls ja sind sie unter avm-logs zu sehen.
Ich nuzte das Syslog Package und hab es so konfiguriert dass es zu einem anderen Gerät im Netzwerk weiterleitet. Dafür brauch man aber irgend einen Syslog-Server.
Die Meldung sieht für mich so aus dass aha (Smart Home) gecrasht ist und der AVM-Watchdog deshlab nach 130 sec einen Reboot ausgelöst hat. Das kann mal vorkommen wenn die AVM-Konfiguration durcheinander komm, zb durch Downgrade.
