### ISSUE TITLE
FREETZ_AVMDAEMON_DISABLE_DNS & FREETZ_AVMDAEMON_DISABLE_DHCP erscheinen nicht bei der 6590

### ISSUE THREAD

**Issue by Conan179** [Freetz-NG/freetz-ng#276]
Ich wollte ein image für meine 6590 bauen, wo die dns und dhcp funktion des multid's ausgeschalten sind.
Die 2 patches sind laut https://github.com/Freetz-NG/freetz-ng/blob/master/config/ui/patches.in noch vorhanden, aber sie werden mir nicht angezeigt
![freetz_dns_18042021](https://user-images.githubusercontent.com/1906242/115144189-9e137a00-a04b-11eb-83ec-b4c4af9b8593.JPG)
![freetz_dns_18042021a](https://user-images.githubusercontent.com/1906242/115144192-a10e6a80-a04b-11eb-850a-bafa5ae455a7.JPG)

**Comment by fda77** [comment]
Da steht auch "depends on FREETZ_AVM_HAS_AVMDAEMON_PRELOAD"
Mit den neueren FOS gibt es keine libctlmgt+libmultid wegen uclibc mehr.  Daher auch keine Optionen dazu.
Als IP Client sollte AVM keine DNS+DHCP starten (ausnahmen: ein Fehler), da man dies bei der Netzwerkconfigugarion angeben muss

**Comment by Conan179** [comment]
Danke für die aufklärung, darauf wäre ich nicht gekommen. Ich kann zwar ein linux per terminal bedinen, aber ein profi bin ich in dem Thema leider nicht -.-
Yay, ich habs mal wieder geschaft nen fehler zu produzieren.
