### ISSUE TITLE
7581/7582: push_firmware issue (memory mapping)

### ISSUE THREAD

**Issue by mikiantena** [Freetz-NG/freetz-ng#289]
[support FRITZ.Box 7582 156.07.14i_01.01.70_0105.txt](https://github.com/Freetz-NG/freetz-ng/files/6423528/support.FRITZ.Box.7582.156.07.14i_01.01.70_0105.txt)
Hi,

I'm trying to upload and use freetz-ng firmware on A1 branded FRITZ!BOX 7582. The current status for this device is (UNTESTED).

I have successfully compiled the minimal image. The only thing I've done so far in `make menuconfig` is to choose my device and leave everything else at their default settings.

The problem arises when I try to upload the generated image file named "7582_07.14.all_freetz-ng-18295-737de89ac_20210504-162606.image".

After trying to upload the image using the official AVM interface which fails because it's not properly signed (or so I've read elsewhere online).

I installed "Freetz-Linux-1.5.8-Ubuntu 20.04.01 LTS (Focal Fossa) 64-Bit" into VirtualBox for all the linux steps to ensure a good working environment. Host system is Arch Linux. (btw ;-))

This is what I've tried so far:
- Upload image with `./tools/push_firmware ` 
- Upload image with `./tools/push_firmware -mr -ram 128`
- Upload image with `./tools/push_firmware -mr -ram 128 -lfs 0`
- Upload image with `./tools/push_firmware -mr -ram 128 -lfs 9`
- Upload image with `./tools/push_firmware -mr -ram 128 -lfs 9 -cmd ncftp`

I tried all of the above with various combinations of RAM size, namely 128, 256 and 512. I got no different results. (Device is 512MB RAM as per AVM support document generated on the device itself)
All of these fail at the point in the script where the file is uploaded e.g. `put /tmp/ramboot.flash "0x85f07c00 0x88000000"`

I then tried to replicate what the shell script is doing manually and enter them into ftp myself. This is a text file I created while doing this:
`debug`
`bin`
`quote MEDIA SDRAM`
`quote SETENV memsize 0x05f07c00`
`quote SETENV kernel_args_tmp mtdram1=0x85f07c00,0x88000000`
`quote P@SW`
`passive`
`put /home/miki/Desktop/FRITZ/freetz-ng/images/7582_07.14.all_freetz-ng-18295-737de89ac_20210504-162606.image "0x85f07c00 0x88000000"`

**The mode of failure is the same as before. I get upload on the order of 4.5KiB/s for around 5 seconds, after which the upload stalls. Around 10 minutes into it I aborted the connection.**

After that I tried forcing single mode with `./tools/push_firmware ~/Desktop/FRITZ/freetz-ng/images/7582_07.14.all_freetz-ng-18270-a2c393eb0_20210503-141326.image -ms`. This actually succeeded procedure wise, but bricked the router. Not completely luckily, the bootloader was still responsive.

Forcing any of the other modes was not working.

The next step was recovering from bricked router, where I used MS Windows Server 2008 R2 under VirtualBox. The official exe recovery (FRITZ.Box_7582-07.14.exe) was complaining:
> Note: The device contains basic settings adapted by your Internet Service Provider (a1_12072017_pdc). Recovery could make the device inoperable on the a1_12072017_pdc network. Please contact your Internet Service Provider instead. Aborting the recovery.

This issue I resolved with known workaround by ftp-ing into the device after failed recovery and issuing `quote UNSETENV provider`. After which I successfully re-ran the rexcovery.

Finally, I have tried to convert the image using `image2ram` and and run it directly from the memory by using `eva_to_memory` from `./tools/yf/eva_tools/`. I have not investigated it too much, but seemingly that fails in similar fashion. Image upload starts with few KiB/s and then stalls.

Please ask for any files, logs or anything that may be of any help. I tried to compile all the relevant information here, but as my development days are behind me (over a decade, now), I might be missing something important. As this device is UNTESTED I am looking forward to working with anybody on this issue. If this is the wrong place for such support, please inform me where to put this information, and delete this issue.

Although my german is rusty, I can read it quite well, however I am unable to reply coherently.

Big thanks,
mantena
MA0

**Comment by fda77** [comment]
UNTESTED means that nobody tested the images on the hardware, as no hardware is available. So it should work, but errors are possible. I have no experience with "provider additive" like a1_12072017_pdc !

0x85f07c00,0x88000000 is the base-address 0x80000000 + allowed maximum ram (option -ram, default 128) - the size of the uploaded image file.
The "nand"/inmemory devices upload on "flashing" the image into the ram (this case: 0x85f07c00) and then boot this, which flashes then itself

Some devices like 6000 are reported not working with 128 default option, they need more like 256
Maybe for 7582 is something special. The best is to use recovery.exe from avm and use tcpdump/wireshark to log (and post here) the ftp-control session and compare the commands

**Comment by mikiantena** [comment]
Hi,

Thanks for the suggestion, I did as you said.

I played around with capture, and noticed that STOR command has a MAPLIMIT of 0x20000000. (512MB)

I also tried replicating the command and I got this so far:
> USER adam2
> PASS adam2
> debug
> quote SYST
> quote SETENV memsize 0x1e1ab000
> quote SETENV kernel_args_tmp mtdram1=0x1e1ab000,0x20000000
> bin
> quote MEDIA SDRAM
> quote P@SW
> passive
> put ramboot.flash "0x1e1ab000 0x20000000"
> quote SETENV linux_fs_start 0
> quote BYE
> quit

I calculated the MTDSTART by subtracting the FILESIZE (31805440 = 0x1e1ab000 in my case) from 512MB (0x20000000).
While the upload is now successful, it does not want to boot from it.
I also tried converting the image with image2ram and upload that (with re-calculated FILESIZE and MTDSTART values of course), but it still won't boot.

I also noticed that in the capture there is no BYE command from the recovery, but it is there when getting the "env" and "count" from  MEDIA_SDRAM.

Between those two downloads from sdram it also stores something to **mtdnand**, like 2,5 kB in size. I'm attaching that part as well.
I'm also attaching only the beginning of sdram STOR (whole is around 32 MB).


Thanks for any further suggestions, your last one was very helpful.

Best regards,
MA0


[recoverydump_STOR_mtdnand.pcap.gz](https://github.com/Freetz-NG/freetz-ng/files/6424327/recoverydump_STOR_mtdnand.pcap.gz)
[recoverydump_STOR_SDRAM_startonly.pcap.gz](https://github.com/Freetz-NG/freetz-ng/files/6424328/recoverydump_STOR_SDRAM_startonly.pcap.gz)

**Comment by fda77** [comment]
The recovery.exe does not only flash, but also factory reset. I think this is  the mtdnand write. The read is for ENV settings like MAC, serial, default (wlan)password etc. But pushfirmware and @PeterPawn script only write the image
BYE: afair this causes a reboot. the bootloader (ftp server) is minimal and after a read no other commands could be executed correctly
pushfirmware can flash inmemory and .image, the format should be detected
follow-tcp-stream from your dump:
```
220 ADAM2 FTP Server ready
USER adam2
331 Password required for adam2
PASS adam2
230 User adam2 successfully logged in
SYST
215 AVM EVA Version 1.3031 0x0 0x4640D
SETENV memsize 0x1e243c00
200 SETENV command successful
SETENV kernel_args_tmp mtdram1=0x1e243c00,0x20000000
200 SETENV command successful
TYPE I
200 Type set to BINARY
MEDIA SDRAM
200 Media set to MEDIA_SDRAM
P@SW
227 Entering Passive Mode (192,168,178,1,17,31)
STOR 0x1e243c00 0x20000000
150 Opening BINARY data connection
```
So the MAPSTART in PF is wrong and should not used for BRCM based devices. I've not yet an idea how to detect it in an image file. Just change
```
--- tools/push_firmware
+++ tools/push_firmware
@@ -82,4 +82,4 @@ function push_fw() {
                        echo
                fi

-               [ $ISRAM ] && MAPSTART=0x80000000 && FILESIZE="0x$(printf '%.8x' $(stat --printf='%s' "$mtdram1"))"
+               [ $ISRAM ] && MAPSTART=0x00000000 && FILESIZE="0x$(printf '%.8x' $(stat --printf='%s' "$mtdram1"))"
```
And run then with "-ram 512"
Upload + boot1 + flash + boot2 should not take more than 3 minutes (maybe 5)

The 7582+7581 are very special devices. Only they have kernel 4.1 and glibc with broadcom. (Kernel-sources are available but not added to freetz yet, they use another directory structure as all other devices.)
And avm uses a sendarp busybox patch only for the 2 devices, which is not made compatible yet with the newer busybox version freetz uses: https://github.com/Freetz-NG/freetz-ng/blob/master/make/busybox/patches/010-brcma9_sendarp.busybox_1-24.avm.patch_fixme Not sure if it is mandatory
The beste way to find the reason why an image does not boot is to attach a serial console which shows what happens. Soldering is great, but a tape should also work for a while ^^

**Comment by mikiantena** [comment]
Thanks for your suggestions so far.

I fixed push_firmware script as per your suggestion. The upload now goes through without any problems.
[push_firmware.fixed.log](https://github.com/Freetz-NG/freetz-ng/files/6429713/push_firmware.fixed.log)

I tried to make the patch for sendarp. With my current profession I'm so far detached from development (think Office as a daily driver for the last 10 years) that I really cannot say anything about it working or not. It does make it into menuconfig and gets compiled without errors. See attached log and patch.

[freetz.make.log](https://github.com/Freetz-NG/freetz-ng/files/6429731/freetz.make.log)
[010-brcma9_sendarp.busybox_1-33.avm.patch.zip](https://github.com/Freetz-NG/freetz-ng/files/6429738/010-brcma9_sendarp.busybox_1-33.avm.patch.zip)

The image is still not working, the device simply hangs after uploading.

I'll open the device tonight and try attaching a serial console to see the actual messages from the system. I'll report back with results as soon as I have any.

Best regards,
MA0

**Comment by mikiantena** [comment]
Hi,

I soldered the connections to serial console. For future reference serial is 3.3V, pretty standard settings 115200, 8N1, VT102.

[minicom_freetzpushfirmware.host.log](https://github.com/Freetz-NG/freetz-ng/files/6430362/minicom_freetzpushfirmware.host.log)
[minicom_freetzpushfirmware.cap.log](https://github.com/Freetz-NG/freetz-ng/files/6430354/minicom_freetzpushfirmware.cap.log)

I only took a quick glance so far and here are my notes:
- Line 130, push firmware put command.
- Line 383, kernel panic
- Line 745, reboot
- Funnily enough with the serial console attached the board boots (into original firmware) instead of freezing like before.

Normal boot follows, captured before push_firmware, just in case any comparisons need to be made.
[minicom_avmboot.cap.log](https://github.com/Freetz-NG/freetz-ng/files/6430375/minicom_avmboot.cap.log)

I do have full access to the original system on serial console, as expected. If any checks are required on my part. I will continue to sift through the logs and filesystem and try to get some sense from it.

After this I tried it again without serial attached. It froze again.
Then I attached only the TX (on 7582) to my RX, and it froze with the following output.
[minicom_freetzpushfirmware_special.cap.log](https://github.com/Freetz-NG/freetz-ng/files/6430419/minicom_freetzpushfirmware_special.cap.log)

On line 385 I attached the RX (on 7582) to my TX on PC, and got the rest of the output in the file.

I hope this helps in any way.

Regards,
MA0

**Comment by PeterPawn** [comment]
You should try first to run the BusyBox made by Freetz's toolchain from an original firmware by AVM - as long as you got your serial console, you're able to copy the needed files (BusyBox binary + C-Library files) to any `tmpfs`-backed location and may call it from there.

The reported `do_undefinstr` sounds like "handle undefined instruction" - this could be the result of wrongly selected compiler options affecting the generated machine code.

Up to the point, where this `do_undefinstr` gets reported, the original kernel from AVM will be executed - the crash occurs at the time, when the first "self-made" component from Freetz (the `init` applet of BusyBox) should get control.

Due to the initial kernel message, AVM has used the settings for a brcma9 processor for kernel compilation:

```
Linux version 4.1.38 (jenkins@ldxjplxmesh18nl2xbrcma9x758xbrcm) (gcc version 5.4.0 (Buildroot 2016.05-gc3ca4dd) ) #1 SMP PREEMPT Wed Mar 17 15:03:45 CET 2021
```

It's only a guess ... based on the shown error indication and the fact, that `cortex-a9` (from your Freetz make log) is a more generic target selection for a `gcc` targeting ARM platforms. There are different capabilities combined in the `cortex-a9` target - see GCC compiler options for ARM: https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

But running the generated binaries with vendor's firmware is the fastest approach to check, whether they're compiled correctly.

**Comment by fda77** [comment]
I noticed in the logs above, but unrelated to the problem: The image contains ipatbles!
AVM has added it to 3 devices so far:
```
7530ax 7.2x+7.25
iptables v1.6.2
some strings:
GCC: (Buildroot 2018.11.4-gef45d7adc) 5.5.0
aeabi
Cortex-A9

7571+7582 7.1x
iptables v1.4.21
some strings:
GCC: (Buildroot 2016.05-gc3ca4dd) 5.4.0
aeabi
Cortex-A9
```

They contains these modules:
```

lib/modules/*/kernel/net/ipv4/netfilter/:
iptable_filter.ko
iptable_mangle.ko
ip_tables.ko
nf_conntrack_ipv4.ko
nf_defrag_ipv4.ko
nf_log_ipv4.ko

lib/modules/*/kernel/net/ipv6/netfilter/:
ip6table_filter.ko
ip6table_mangle.ko
ip6table_raw.ko
ip6_tables.ko
nf_conntrack_ipv6.ko
nf_defrag_ipv6.ko
nf_log_ipv6.ko
```

All other devices uses avm's closed source multid blob to route, forward, etc. conntrack and related dont work as avms module packet-accelerator causes crashes

**Comment by fda77** [comment]
@mikiantena If you copy a binary to the device you may need libc too: https://freetz-ng.github.io/freetz-ng/NEWS.html#2021-05-05

**Comment by mikiantena** [comment]
Thanks for good suggestions and instructions.

First short test shows that busybox is working. I include logs to show what I did exactly. I couldn't think of any way to run freetz busybox (and have it see linked libraries) other than using the chroot supplied by AVM's busybox. I hope my solution is ok.

[busybox_fileinfo.log](https://github.com/Freetz-NG/freetz-ng/files/6435843/busybox_fileinfo.log)
[busybox_test.log](https://github.com/Freetz-NG/freetz-ng/files/6435845/busybox_test.log)

All the files tested were copied from `~/freetz-ng/build/modified/filesystem/`.

A small curiosity: After the first basic test, I ran several "busybox who" (freetz busybox, not AVM one), and the first run gave me `do_undefinstr` `Illegal instruction`, other two showed up empty. I included this in my logs.

@PeterPawn I see that cross compiling is not as straightforward as native, and I have no prior experience in the matter. I'll read on it and see how to target brcma9 processor specifically. Thanks for the heads-up and reading material.

@fda77 You say this iptables stuff should be unrelated to the problem, but let me know if I can or should disable or modify anything for elimination purposes (Or were you simply excited to see full iptables implementation?)

I'll get back to you with any results I may have.

Best regards and thank you guys for your time and attention to this problem,
MA0

**Comment by fda77** [comment]
Seems PeterPawn is right with wrong compiler options. If you change them, you have to enable "Build own toolchains" in menuconfig, take about 20 minutes to build

I'm not sure if chroot causes some problems. Just set FREETZ_RPATH in menuconfig to test binaries only ("not found" as it runs on my computer):
```
$ toolchain/build/arm_gcc-5.5.0_uClibc-1.0.37-nptl_kernel-4.1/arm-linux-uclibcgnueabi/bin/arm-linux-uclibcgnueabi-ldd \
    packages/target-arm_gcc-5.5.0_uClibc-1.0.37-nptl_kernel-4.1/busybox/busybox
checking sub-depends for 'not found'
        libc.so.0 => not found (0x00000000)
        /tmp/mylibs/ld-uClibc.so.1 => /tmp/mylibs/ld-uClibc.so.1 (0x00000000)

```
On my 7490
```
ldd /bin/busybox
        libc.so.0 => /tmp/mylibs/libc.so.0 (0x7710c000)
        ld-uClibc.so.1 => /tmp/mylibs/ld-uClibc.so.1 (0x771e1000)

```

iptables: For the first dont select iptables in menuconfig, it could overwrite avm files with something not compatible

Another idea for the cause of the problem: Wrong kernel sources! Afaik it should only matter
 - with (self build) replace kernel 
 - additional kernel modules
 - some packages using headers, like smartmontools which need some scsi*h

1+2 is disabled in menuconfig atm

Here is a small how to add the sources: https://github.com/Freetz-NG/freetz-ng/blob/master/config/avm/source.in#L317
The problem is the last item on the list

**Comment by mikiantena** [comment]
You're right that my chroot solution was messing with something.

After setting FREETZ_RPATH, recompiling and running I get:
```
# pwd
/var/media/chroot
# find
.  
./usr  
./usr/lib  
./usr/lib/freetz
./usr/lib/freetz/ld-uClibc.so.1
./usr/lib/freetz/libthread_db-1.0.37.so
./usr/lib/freetz/libthread_db.so.1
./usr/lib/freetz/ld-uClibc.so.0
./usr/lib/freetz/libc.so.0
./usr/lib/freetz/libc.so.1
./usr/lib/freetz/libgcc_s.so.1
./usr/lib/freetz/libuClibc-1.0.37.so
./usr/lib/freetz/libgcc_s.so
./usr/lib/freetz/ld-uClibc-1.0.37.so
./usr/lib/freetz.tar
./busybox
./bb.tar
# ./busybox
do_undefinstr
Illegal instruction
`
Changing compiler options seems to be the route to go, I'll continue working on it.

Cheers

**Comment by fda77** [comment]
I dont know, im not en expoert in this! Do other compiled binaries work? If only Busybox has a problem it could be an option in menuconfig>busybox>settings

**Comment by mikiantena** [comment]
Just a quick update. I've gotten somewhere....kind of.

As far as other binaries are concerned, earlier in the day I tried running modcgi, which failed in the same fashion as busybox.
[bintest_modcgi.log](https://github.com/Freetz-NG/freetz-ng/files/6438036/bintest_modcgi.log)

Then I tried changing the build environment to brcma9. Again, not sure if I'm doing this correctly.
[brcma9_make_test.patch.zip](https://github.com/Freetz-NG/freetz-ng/files/6437994/brcma9_make_test.patch.zip)

The build actually failed:
[brcma9_make_error.log](https://github.com/Freetz-NG/freetz-ng/files/6437999/brcma9_make_error.log)

But I noticed that busybox and uClibc got built, so I transferred them to the router. And as you can see from the logs, a single run of busybox showed the available commands. After that I got hit with Illegal instruction again. System was still responsive, but I just couldn't get busybox to run again.
[bintest_busybox_brcma9.log](https://github.com/Freetz-NG/freetz-ng/files/6438023/bintest_busybox_brcma9.log)

I've never experienced that a binary would run fine once, and then... simply not run again. After trying couple of times, I ran the AVM busybox  just to verify the difference in busybox versions. I'll try again tomorrow, perhaps build it from a completely clean environment (I did run make clean after changing config files), but at least it seems that we're on the right track and I got some promising results.



Best regards, MA0

**Comment by PeterPawn** [comment]
Check thoroughly, whether BusyBox and uClibc are really depending on `libgcc.so` - if it's true, you HAVE to rebuild the whole toolchain from scratch, because code in `libgcc` is platform-dependent and this library will be created while building the compiler toolchain.

And I'm not sure, whether your patch attempt has the wanted result - even if it looks like Freetz-NG would be supporting builds for 7539 and this device would use the needed compiler settings, too, I'd think, this part was never tested - simply due to the lack of available devices in the wild.

If you had a glance at the open source package provided by AVM for 7582 devices, you'll see, that this model was obviously started with an internal model number 7569 - it's not the first case, where AVM had changed these numbers once more, before a device got really available at the market.

I had only a short impression yet from Freetz-NG settings and the differences between FREETZ_SYSTEM_TYPE_BCM63138 and FREETZ_SYSTEM_TYPE_BRCMA9 - as I've seen so far, I'd tend to say, only a different base package for kernel sources gets selected, but no different compiler settings.

But to make sure, whether my impression is true, you should compare a compiler call - and especially the used options - for both selections. All three models with this Broadcomm chipset family (7581, 7582, 7530ax) seem to be untested yet in Freetz-NG - possibly all of them use the wrong compiler settings, too.

Some hints regarding the needed settings may be found in the file `make.common` (adapted by AVM in some aspects, but made by Broadcomm) around line 530 - it may be found in the open-source package published by AVM for 7582 models (for compiler settings it doesn't matter, whether the FRITZ!OS version is current).

**Comment by mikiantena** [comment]
Sorry for taking this long to respond. I had some family obligations and was away for several days.


I git cloned all the freetz-ng code into a clean build path and applied the compiler patch from @fda77.
In menuconfig I only configured the FREETZ_RPATH and my router type, as well as made sure that build own toolchain was selected (which it was by default, and I was not able to change it).

Sadly I still get `do_undefinstr` and `Illegal instruction` after running busybox. It's consistent this time, I tried spamming it as fast as I could to see if one core is different this time.

I should have more time after work today and will play some more with compiler options.
I welcome any further suggestions.

Best regards

**Comment by fda77** [comment]
Sorry, i have no more ideas, but i hope @PeterPawn has

**Comment by PeterPawn** [comment]
I'd like to point out again, that the (hopefully) correct compiler settings may be found at the (above) mentioned location. After adopting these settings for the appropriate models, a `make` call reveals, how a compiler command looks like - if someone shows the log-file of this attempt. This is in my opinion the only serious option to check, whether the used cross-compiler environment looks good or odd. 

Further attempts to run any created binary, without a first step to ensure proper compilation, are (imho) useless - the primary goal (to make sure, that none of the created binaries are able to run and therefore the compilation wents wrong) was reached already and now no further trial and error is needed, but a correct adaption of needed settings to available Freetz(-NG) options/settings.

**Comment by PeterPawn** [comment]
The title of this discussion has to/should be changed ... it's not only the `push_firmware` issue anymore and it's hard to find the "compiler options theme" by its title.

I'm looking for a good place, too, to add some comments to the changes regarding the `-map` option of `push_firmware` (https://github.com/Freetz-NG/freetz-ng/commit/351542256a934990fcdff26e14bce7166b2d887c) - this thread had could it be, but not after its conversion to "binary format problems with some Broadcomm chipsets".

**Comment by fda77** [comment]
Github does not allow to split issues/move posts. So add a issue about compiler options?

**Comment by PeterPawn** [comment]
This would be my suggestion (edited above) - as written there, it should/could contain a link to this one here to avoid duplicate posts, but still provide a better (and findable) location for the 2nd and unrelated problem.

**Comment by fda77** [comment]
7581/7582: wrong compiler options -> https://github.com/Freetz-NG/freetz-ng/issues/301
