### ISSUE TITLE
Makefile:275: recipe for target 'firmware-nocompile' failed

### ISSUE THREAD

**Issue by syncgw** [Freetz-NG/freetz-ng#29]
Hi,
I just cloned your fork with `svn co https://github.com/Freetz-NG/freetz-ng/trunk ~/freetz-ng` and tried to compile on a hyper-v "Ubuntu 18.04.3 LTS" (Win10). Unfortunately compile broke :-(
```
make
fakeroot: FAKEROOTKEY set to 2020429160
fakeroot: nested operation not yet supported
Makefile:275: recipe for target 'firmware-nocompile' failed
make: *** [firmware-nocompile] Error 1
```
Any how to solve?

**Comment by fda77** [comment]
Easiest to resolve is to use a real Linux...
I have no Windows with WSL support, so i don't know anything about it
Here's a link to a VM which works for freetz: https://github.com/Freetz-NG/freetz-ng/blob/master/README.md#readme

In case you want to make freetz work with WSL:
 * https://www.ip-phone-forum.de/297537/
 * https://trac.boxmatrix.info/freetz-ng/ticket/2854

**Comment by fda77** [comment]
The patch from IPPF is added

**Comment by fda77** [comment]
Sry, link to ippf was broken: https://www.ip-phone-forum.de/threads/297537/
