### ISSUE TITLE
Patch will not be applied

### ISSUE THREAD

**Issue by vx-i** [Freetz-NG/freetz-ng#290]
I would like to upgrade my AVM 1750e with Freetz-NG. Specifically, I would like to use my own certificates. There is a patch from the community for this ([link](https://www.ip-phone-forum.de/threads/wlan-repeater-1750e-modifizieren.301663/page-3#post-2307401)). I've stored the file here: patches/devices/07_0X/1750/ and build the firmware, but the patch was not applied. I would appreciate a little help or a hint.

PS: I used 7.24 labor firmware.

**Comment by fda77** [comment]
When you put the patch in 07_0X you have to select 7.0x in menuconfig
