### ISSUE TITLE
Telekom Links tot

### ISSUE THREAD

**Issue by sfritz2** [Freetz-NG/freetz-ng#309]
z.B. für Speedport W900V. Als Alternative könnte man auf web.archive.org verlinken: http://web.archive.org/web/20120808073547/http://www.telekom.de/dlp/eki/downloads/Speedport/Speedport%20W%20900V/fw_Speedport_W900V_v34.04.57.image

**Comment by fda77** [comment]
Bei vielen alten Firmwaredateien sollte es keinen offiziellen DL-Link mehr geben
Die URLs sind jedenfalls hier drin: https://github.com/Freetz-NG/freetz-ng/blob/master/config/mod/download.in

**Comment by fda77** [comment]
Ich denke nicht dass man das brauch. Wer es möchte muss es machen
