### ISSUE TITLE
src 7490

### ISSUE THREAD

**Issue by freetz-ng-mod** [Freetz-NG/freetz-ng#313]
https://osp.avm.de/fritzbox/fritzbox-7490/source-files-FRITZ.Box_7490-vr9-07.27.tar.gz
https://osp.avm.de/fritzbox/fritzbox-7490/source-files-FRITZ.Box_7490-vr9-07.26.tar.gz
https://osp.avm.de/fritzbox/fritzbox-7490/source-files-FRITZ.Box_7490-scrpn-07.27.tar.gz

**Comment by fda77** [comment]
-> diskussions

**Comment by freetz-ng-mod** [comment]
Man kann die src auch für die 5490 und 5491 nutzen denn die neuen FW greifen immer noch auf 7.01 src

**Comment by fda77** [comment]
Es hätten schon vorher die 07.21 sein sollen

**Comment by freetz-ng-mod** [comment]
nein war es leider nicht aber auch nun egal

**Comment by fda77** [comment]
Das kann nicht sein
