### ISSUE TITLE
[module] module file not found but it is there

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#36]
I have a config file but it is not working anymore (latest working build tested by me 18/07/2020).

The module is there but cannot be found (difference - / _ in the name)?

![module_not_found](https://user-images.githubusercontent.com/14336586/89223513-34476300-d5d7-11ea-9c7c-1b92c077c106.png)

[config.txt](https://github.com/Freetz-NG/freetz-ng/files/5018256/config.txt)

**Comment by fda77** [comment]
The messages are new https://github.com/Freetz-NG/freetz-ng/commit/cce60e94522601c019033ab43d9e73fa5688f75e and to exactly, as variable names can not contain "-"
This should help:
