### ISSUE TITLE
RRDstats SmartHome – fehlerhafte Anzeige Button Änderung Solltemperatur

### ISSUE THREAD

**Issue by leo-022** [Freetz-NG/freetz-ng#369]
Bedingt durch die beiden von AVM vorgegebenen Werte 253 (aus) und 254 (ein) erfolgt am jeweiligen Button auf der Seite Status -> SmartHome eine falsche Anzeige der Temperatur:
![Button](https://user-images.githubusercontent.com/87432648/129862426-d537c33b-d8ce-4f4f-a505-a32b04e21769.png)
Statt 126,5°C müsste „aus“ und statt 127 „ein“ angezeigt werden. Dieses Verhalten tritt z. B. auf, wenn im AVM-Webinterface ein Heizung-aus-Zeitraum festgelegt wurde und dieser gerade aktiv ist.

Die Auswertung erfolgt in /usr/lib/cgi-bin/rrdstats/main.cgi ab Zeile 1390. Da der Wert durch 2 geteilt wird, erscheinen 126,5 und 127.
```
if [ -n "$tsoll" ]; then
   soll="$(echo $(( ${tsoll}0 / 2)) | sed 's/.$/,&/g')"
   temps=" (${grad%,0}->${soll%,0})"
```
Ebenso müsste auch im Eingabefenster die Eingabe der Werte 253 und 254 möglich sein (Multiplikation mit 2 nicht für diese beiden Zahlen).
```
butact="onclick=\"val = prompt('Solltemperatur (8-28):');if (val) window.location=('$SCRIPT_NAME?pdev=$pdev$refresh&ain=$ain&state='+parseFloat(val.replace(',','.'))*2)\""
```

**Comment by fda77** [comment]
Ich hab wie gesagt on/off nie benutzt. Müsste halt jemand das bestehende erweitern. Ich schiebs mal auf die Wishlist
