### ISSUE TITLE
MiniDLNA doesnt start at boot.

### ISSUE THREAD

**Issue by ektorasdj** [Freetz-NG/freetz-ng#376]
Hello and thank you for this fine mod for my fritzbox 7530. I have the latest fritzos with the the latest freetz-ng.
The problem existed since older versions.
Even though i have the setting for mini dlna to start automatically if i reboot my fritzbox or remove the power cable and reconnect it everything starts fine but the minidlna service is stopped.I have to start it manually.
The only extension i have installed in freetz-ng is the minidlna.Its the only thing i use.
I have the fritzbox connected to ups so its not a big problem since there must be a power outage long enough for the ups to shutdown but still if its something easily fixable i would really like for someone to help me .
Thanks.
Same problem happens on my father's 7580 fritzbox.

**Comment by fda77** [comment]
-> https://github.com/Freetz-NG/freetz-ng/discussions/368
