### ISSUE TITLE
dbus expat build error 

### ISSUE THREAD

**Issue by Fabus1184** [Freetz-NG/freetz-ng#378]
when compiling I get the error:

```
checking for XML_ParserCreate_MM in -lexpat... no
configure: error: Explicitly requested expat but expat not found

ERROR: Build failed.
make: *** [make/dbus/dbus.mk:59: source/target-mipsel_gcc-4.6.4_uClibc-0.9.32.1/dbus-1.8.20/.configured] Fehler 1
```

altough dbus isn't even selected to install and expat and libexpat are installed

**Comment by fda77** [comment]
Freetz uses current libexpat version, but dbus from (year) 2014 ...
Im not sure if updating make/dbus/dbus.mk breaks something else
