### ISSUE TITLE
busybox 1.34: freetz web stucks

### ISSUE THREAD

**Issue by flosch-dev** [Freetz-NG/freetz-ng#381]
Ich habe busybox auf 1.34 umgestellt und nun hängt leider das web-interface. Ob es daran liegt kann ich leider noch nicht sagen.
Ich sehe noch die Kopfzeile, aber danach lädt es einfach bis zum timeout weiter ohne einen Inhalt zu empfangen.
Leider passiert auch das gleich beim laden der firmware update site :(

![image](https://user-images.githubusercontent.com/47741987/132404744-e271c637-c79f-40b7-b28a-76e8fb2cb0b0.png)

Gibt es einen Weg über SSH eine neue Firmware zu laden? Ich habe direkt vom gleichen build eine Version mit busybox 1.33 erstellt und wollte diese nun testen.

**Comment by berndy2001** [comment]
Lebt das AVM-Webif noch? Dann probiers mal dort.

**Comment by fda77** [comment]
Ist bei mir auch so. Der Aufbau des Menüs hängt: `/bin/sh -x /usr/lib/mod/menu-update`
Wenn du das Image mit dem gleichen Computer gebaut hast (mit dem gleichen Key signiert hast) kannst du Freetz über das AVM-Webif flashen.
Oder per SSH schauen: `cat /proc/sys/urlader/environment` und ändern: `echo "linux_fs_start 0oder1" > /proc/sys/urlader/environment` + reboot

**Comment by flosch-dev** [comment]
Danke für den Hinweis, habe über SSH die anderen partition geladen und dann nochmal ein FW upgrade durchgeführt.
Schon eine Idee was da genau hängt?

**Comment by fda77** [comment]
Ich hab keine Ahnung weshalb genau diese 2 `source` Befehle "hängen". In den Dateien befindet sich nur ein `title='abc'`. Von einem eigenen Script aus funktioniert es. Es kann ein Bug in BusyBox sein (die .0 wird da immer experimentell genannt) oder daran liegen wie das ganz Freetz-Webif geschrieben ist. Buehmann hatte überall sehr komplizierte Konstrukte verwendet.

**Comment by fda77** [comment]
https://github.com/Freetz-NG/freetz-ng/issues/381

**Comment by fda77** [comment]
Sollte behoben sein, müsste aber noch jemand testen!
 - https://git.busybox.net/busybox/commit/?h=1_34_stable&id=76ef4391548ded8db511e2f7f8f35a3010be7ec5
 - https://github.com/Freetz-NG/freetz-ng/commit/33e3edc254f06a61f07fff9aea895ced53335f50
 - https://github.com/Freetz-NG/freetz-ng/commit/05bd379b395f399a91661a1dbf449a28ecc1aef2
