### ISSUE TITLE
Dnsmasq 2.86 exits on reload/SIGHUP

### ISSUE THREAD

**Issue by flosch-dev** [Freetz-NG/freetz-ng#397]
Hallo,
ich habe aktuell das Problem dass der dnsmasq Prozess sich immer wieder beendet. Das Problem tritt erst seit dnsmasq dem letzten upgrade auf 2.86 (https://github.com/Freetz-NG/freetz-ng/commit/86f8c118732c6192a652b360fd757bd3d24ec08e) auf. 
Mittlerweile konnte ich erkennen, dass der Prozess immer nach einen "/etc/init.d/rc.dnsmasq reload" beendet ist.
Leider bekomme ich auch keine Fehlermeldung insofern bin ich unsere ob dnsmasq crash oder auf Grund von modlib_reload irgendiwe beendet wird.
Vielleicht hat jemand eine Idee woran es liegen könnte?
ich nutze zusätzlich addhole, aber habe auch alle hosts gelceared und leer gelassen, trotzdem das gleiche problem beim reload.

**Comment by fda77** [comment]
Da es wohl ein dnsmasq Problem ist schliesse ich das hier. Du musst du halt auf der Mailingliste von dnsmasq nachfragen, dafür gibt es nur diese mittelalterliche Art Probleme zu melden.
Fall dir ein gewisser "Geert Stappers" dort antwortet, ignorier ihn am besten. Das ist ein bekannter Troll bei debian und dnsmasq.
In 2.86 gibt es wohl noch andere Ursachen für Crashes, wenn man über https://www.mail-archive.com/dnsmasq-discuss@lists.thekelleys.org.uk/maillist.html liest
