### ISSUE TITLE
5530 Kernel 4.9.231

### ISSUE THREAD

**Issue by freetz-ng-mod** [Freetz-NG/freetz-ng#408]
Bei der 5530 ist aus dem Kernel 4.9.218 Kernel 4.9.231 geworden

**Comment by fda77** [comment]
Ja: https://github.com/Freetz-NG/freetz-ng/blob/master/config/.img/5530--07_25.in#L9
Falls du damit sagen willst dass es keinen Sourcecode gibt: https://freetz-ng.github.io/freetz-ng/SUPPORT.html#quellcode

**Comment by fda77** [comment]
Und https://github.com/Freetz-NG/freetz-ng/discussions/134

**Comment by freetz-ng-mod** [comment]
Wenn du schon Sachen aus dem Kernel löschen lassen willst, brauchst du ein Kernel 4.9.231 Verzeichnis 
https://github.com/Freetz-NG/freetz-ng/blob/master/make/linux/patches/4.9.218/001-regular_dot_config_location.patch

**Comment by fda77** [comment]
Der commit comment lautet "add 5530 src"...

**Comment by freetz-ng-mod** [comment]
so
das soll aus der .kernelvariables gelösdcht werden
-export AVM_KCONFIG_CONFIG = avm/conf/linux-4.9.prxI
aber wir brauchen für Kernel 4.9.218 aber das
export AVM_KCONFIG_CONFIG = avm/conf/linux-4.9.grx5
Und wie ich schon sagte die 5530 ist nun 4.9.231

**Comment by fda77** [comment]
Sagtest du schonmal ebenso ohne Zusammenhang und ich antwortete in https://github.com/Freetz-NG/freetz-ng/issues/408#issuecomment-968327314 darauf. Ich hab aber noch immer nicht durchblickt was du damit sagen willst. Was soll das denn heissen?
