### ISSUE TITLE
Unable to build freetz-ng on debian bullseye

### ISSUE THREAD

**Issue by parided** [Freetz-NG/freetz-ng#409]
Hi,
I'm unable to build freetz-ng on debian 11 Bullseye.
I try to download a ready-to-use VM like Gismotro's Freetz-Linux, but firex or chrome, tell me:
This site can’t be reached freetz.digital-eliteboard.com refused to connect.
When I connect without https, the site appear to the default apache installation

Are you be able to post a precompiled image for 7270 v3?

**Comment by parided** [comment]
feetz.digital-eliteboard.com  is online again.
Sorry

**Comment by fda77** [comment]
You should update your checkout, there are now additional mirrors
