### ISSUE TITLE
Update PCSC-Lite 1.8.24 zu PCSC-Lite 1.9.0 und libusb  zu libusb 1.0.23

### ISSUE THREAD

**Issue by MasterRoCcO** [Freetz-NG/freetz-ng#41]
Hi kannst du das PCSC-Lite 1.8.24 zu PCSC-Lite 1.9.0 Updaten
https://pcsclite.apdu.fr/files/pcsc-lite-1.9.0.tar.bz2

libusb 1.0.23
https://github.com/libusb/libusb/releases/tag/v1.0.23
Denn wenn man mit S3 nun ein oscam baut und das nun auf der fritzbox nutzen will geht dieses nicht weil was fehlt in denn alten sachen die in freetz sind

Error relocating /usr/lib/freetz/libusb-1.0.so.0: __assert: symbol not found
Error relocating /usr/lib/freetz/libusb-1.0.so.0: fcntl64: symbol not found

**Comment by fda77** [comment]
Kann ich wahrscheinlich, mir ist es aber lieber wenn du es selbst versuchst!
Schau mal hier https://freetz-ng.github.io/freetz-ng/SUPPORT Dort "Package bump" und "Pull request". Nach Möglichkeit nur 1 Commit pro Packache bzw Library!
Ich glaub CCID wurde immer gleichzeitig mit PCSC erhöht, könnte deshlab auch nötig sein

**Comment by MasterRoCcO** [comment]
das habe ich noch nie gemacht. Werde es aber mal versuchen die Tage

**Comment by forenuser** [comment]
https://github.com/Freetz-NG/freetz-ng/issues/44 könnte vielleicht auch hierbei relevant sein.

**Comment by forenuser** [comment]
Wer weiß, ob die Aktualisierung überhaupt nötig ist.

- **Ich sage Adios und viel Erfolg mit Deinem Project. Versuche mal runterzukommen von Deinem hohen Ross!**

**Comment by fda77** [comment]
-> https://github.com/Freetz-NG/freetz-ng/pull/47
