### ISSUE TITLE
VM OVA 100GiB?

### ISSUE THREAD

**Issue by Sysadminfromhell** [Freetz-NG/freetz-ng#421]
Can u maybe cleanup and shrink the VM OVA File to approx 25 GB or less?
I had to Import a 100 GiB File to my 500 GiB Storage, kind of overkilling for just the "making" of the Firmware Package isnt it?

**Comment by fda77** [comment]
Freetz-Linux-1.7.2 is just 3GB. But freetz does not provide a VM and is not realted. Please as Gismotro https://www.ip-phone-forum.de/ or https://www.digital-eliteboard.com/
