### ISSUE TITLE
Unable to update Fritz OS

### ISSUE THREAD

**Issue by Pixelramp** [Freetz-NG/freetz-ng#472]
Currently, my Fritzbox 6591 Cable is running on 161.07.28 (07.28).

I'm trying to update to 07.29. But after uploading the new Image, I'll receive this message.
![2022-02-21 15_56_48-Freetz – Firmware-Update – Opera](https://user-images.githubusercontent.com/38528427/154979937-b09646e0-4bf3-4f42-a7b3-b09f194a21c8.png)

**Comment by Pixelramp** [comment]
> 

It's actually not a downgrade.  I have no idea why Freetz calls it a downgrade. 

It should be an upgrade from 7.28 to 7.29

Updating via the avm gui results in this Error : 

firmwarecfg: ERROR
Error: opening page ../html/tools/update_result_noreboot.html

**Comment by fda77** [comment]
Tried without ticking the "downgrade" checkbox?
By AVM gui it works only if the signature matches

**Comment by Pixelramp** [comment]
Yes
![2022-02-21 16_14_57-Freetz – Firmware-Update – Opera](https://user-images.githubusercontent.com/38528427/154982731-6d7fabfd-17f4-4f2a-8c2f-97732a11a6b5.png)
Same result without the downgrade

Is a mismatching signature the cause for the firmwarecfg: ERROR  error?

**Comment by fda77** [comment]
Okay, then freetz-flash does not work. But it always work to flash an avm image by avm gui

**Comment by Pixelramp** [comment]
It sould work but it results into

firmwarecfg: ERROR
Error: opening page ../html/tools/update_result_noreboot.html

But i think thats more a AVM problem than a Freetz problem.. 

It's sad that there is no recover tool for the Cable versions.. 


It's been a while since i flashed the freetz image, so i need to look into it to flash the normal Image

**Comment by fda77** [comment]
Maybe you made some branding "magic"?
Try to flash with tools/push_firmware or https://bitbucket.org/fesc2000/ffritz/src/6591/README-6591.md

**Comment by Pixelramp** [comment]
Ok, I've tried pushing the avm image via the push_firmware tool. But the tool seems to be stuck here 
![20220221_180401.jpg](https://user-images.githubusercontent.com/38528427/154999524-a6be4126-733c-4bd5-9c81-1d720ea1b2d8.jpg)

The info led lights up red and the power led is blinking green.

Should I wait longer or is there something wrong?

**Comment by Pixelramp** [comment]
Ok, i successfully flashed the avm image via the flashtool. 

Thank you for the help! Now I can do the flashing for freetz again and hopefully updating will work the next time!
