### ISSUE TITLE
avm-firewall not available in newer versions

### ISSUE THREAD

**Issue by oli-z** [Freetz-NG/freetz-ng#478]
Hi,

I wanted to ask if there is any reason, why the avm-firewall package is not available with newer FRITZ!OS versions. If I comment out the dependency it is available again.

Is there a reason why this old version dependency is there and are there any problems with commenting it out and using the package anyway? Just curious.

Thanks

**Comment by fda77** [comment]
-> https://freetz-ng.github.io/freetz-ng/make/avm-portfw.html

**Comment by oli-z** [comment]
> -> https://freetz-ng.github.io/freetz-ng/make/avm-portfw.html

This works for port forwardings, but is there also a way to block outgoing connections to certain IPs?

**Comment by fda77** [comment]
No. For simple DROP/REJECT you could use iptables, which works as long as you dont state/conntrack
