### ISSUE TITLE
Wireguard Status reported inaccurately on "Services"-Overview

### ISSUE THREAD

**Issue by hoewer** [Freetz-NG/freetz-ng#484]
For several months now the status of Wireguard on the services overview is reported as stopped, even though it is up and running flawlessly.
![Freetz1](https://user-images.githubusercontent.com/90464130/155952523-45147c68-4a74-4ecf-a4b4-879f23de62e9.jpg)

On the detailed Wireguard overview the status is reported correctly
![Freetz2](https://user-images.githubusercontent.com/90464130/155952669-6fb86ce7-7f62-4b3e-b5ea-57b3db070e88.jpg)

I'm on FB 7490, freetz-18925MA.

It is only a minor problem, but I decided to report it anyway.

**Comment by fda77** [comment]
https://github.com/Freetz-NG/freetz-ng/blob/master/make/wireguard/files/root/etc/init.d/rc.wireguard#L5

> DAEMON_CHECK=wg-crypt-$WIREGUARD_INTERFACE

Can you check which processes are running? Maybe `WIREGUARD_INTERFACE` is not yet set there

**Comment by hoewer** [comment]
Wireguard interface seems to be up and running, connections are built up easily:

4792 root 0 SW< [wg-crypt-wg0]

<details>
  <summary>Click to expand full process list!</summary>
  
  ## Result of 'ps'
  PID USER       VSZ STAT COMMAND
    1 root      1840 S    init
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    5 root         0 SW<  [kworker/0:0H]
    7 root         0 SW   [migration/0]
    8 root         0 SW   [rcu_bh]
    9 root         0 SW   [rcu_sched]
   10 root         0 SW   [watchdog/0]
   11 root         0 SW   [watchdog/1]
   12 root         0 SW   [migration/1]
   13 root         0 SW   [ksoftirqd/1]
   15 root         0 SW<  [kworker/1:0H]
   20 root         0 SW<  [khelper]
   21 root         0 SW   [kdevtmpfs]
  134 root         0 SW<  [writeback]
  137 root         0 SW<  [bioset]
  138 root         0 SW<  [crypto]
  140 root         0 SW<  [kblockd]
  241 root         0 SW   [kswapd0]
  242 root         0 SWN  [ksmd]
  243 root         0 SW   [fsnotify_mark]
  250 root         0 SW   [temp_reader_CPU]
  772 root         0 SW   [pm_info]
  777 root         0 SW<  [eventsink_wq]
  780 root         0 SWN  [avm_debugd]
  896 root         0 SW<  [ipv6_addrconf]
  903 root         0 SW   [tffsd]
  904 root         0 SW<  [deferwq]
  907 root         0 SW<  [avmnet_workqueu]
  908 root         0 SW<  [PhyWaspHeartbea]
  924 root         0 SW<  [avmnet_timer]
  930 root         0 SW<  [loop0]
  959 root         0 SW   [cleanup_timer_f]
  960 root         0 SW   [avm_connect_eve]
  961 root         0 SW<  [eventsink_wq]
  962 root         0 SW<  [eventsink_wq]
  977 root      1528 S    supervisor /lib/systemd/system
  994 root         0 SW   [yaffs-bg-1]
 1130 root      1840 S    init
 1183 root     30400 S    /usr/bin/untrustedd
 1678 root      3244 S    /sbin/udevd
 2495 root         0 SW<  [eventsink_wq]
 2516 root         0 SW<  [capi_pipew]
 2517 root         0 SW<  [capi_schedw]
 2518 root         0 SW<  [eventsink_wq]
 2519 root         0 SW<  [kworker/1:1H]
 2520 root         0 SW   [pcmlink_ctrl/1]
 2522 root         0 SW   [capitransp]
 2535 root         0 SWN  [kneightrackd]
 2567 root         0 SW<  [avm_dect_thread]
 2644 root         0 SW   [yaffs-bg-1]
 2682 root      3836 S    /bin/avmipcd
 2688 root      1488 S    /bin/run_clock -c /dev/tffs -d
 2689 root      2512 S    /sbin/psetd /etc/psetd.cfg
 2696 root      2764 S    /usr/bin/boxnotifyd
 2717 root      2796 S    /bin/configd
 2794 root      7160 S    avmnexusd
 2819 root      4608 S    l2tpv3d
 2850 root     10268 S    dsl_control -i10_00_10_40_00_04_01_07 -f/lib/modules
 2856 root      8056 S    dsl_monitor -d
 2863 root     32468 S    ctlmgr
 2871 root      5548 S    vpnd
 2876 root         0 SW   [autbtex]
 2877 root         0 SW   [pmex_ne]
 2878 root         0 SW   [pmex_fe]
 2880 root     14788 S    upnpd
 2966 nobody    5684 S    dnsmasq --pid-file=/var/run/dnsmasq/dnsmasq.pid --re
 2992 root      8396 S    multid -d
 3076 root      6880 S    ddnsd
 3080 root      4140 S    pcpd
 3090 root      8988 R    wland -B
 3109 root      6660 S    dsld -i -n
 3148 root      4020 S    deviceinfod
 3152 root     20368 S    {aha_main} /usr/bin/aha
 3228 root      6168 S    pbd
 3235 root         0 SW   [khubd]
 3344 root     14456 S    telefon a127.0.0.1
 4065 root     14776 R    meshd
 4134 root     10096 S    dect_manager
 4217 root      1780 S    httpd-webcfg -P /var/run/webcfg.pid -p 81 -c /mod/et
 4254 root      9872 S<   voipd
 4380 root      3956 S    /bin/voipkpid
 4416 root      7752 S    feedd
 4444 root         0 SW   [avmcsrpc]
 4455 root      4496 S    pictured -Dpicserver -Dhandheld -Dsequence -Dpicdb -
 4457 root      1780 S    inetd
 4472 root      4444 S    audiod
 4574 root      1572 S<   log_server -d -t 0 -i wasp -w 20 4201 /var/log/panic
 4578 root      2464 S<   log_server -d -t 0 -i wasp -w 20 4202 /var/log/debug
 4580 root      2464 S<   log_server -d -t 0 -i wasp -w 20 4210 /var/log/wland
 4583 root      1572 S<   log_server -d -t 0 -i wasp -w 20 4211 /var/log/hosta
 4590 root      2464 S<   log_server -d -t 0 -i wasp -w 20 4212 /var/log/wpa_s
 4593 root      2464 S<   log_server -d -t 0 -i wasp -w 20 4213 /var/log/acfg.
 4598 root      2464 S<   log_server -d -t 0 -i wasp -w 20 4214 /var/log/crash
 4736 openvpn   4748 S    openvpn --config /mod/etc/openvpn.conf --writepid /v
 4792 root         0 SW<  [wg-crypt-wg0]
 4867 root      4912 S    usermand
 4881 root      6100 S    contfiltd
 4988 root     18932 S    privoxy --pidfile /var/run/privoxy.pid /mod/etc/priv
 5143 root      1780 S    httpd-wol -P /var/run/webcfg-wol.pid -p 84 -c /mod/e
 5503 nobody    3116 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5511 nobody    3248 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5512 nobody    3116 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5513 nobody    3208 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5514 nobody    3212 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5518 nobody    3228 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5519 nobody    3228 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5520 nobody    3208 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5521 nobody    3220 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5522 nobody    3220 S    tinyproxy -c /mod/etc/tinyproxy.conf
 5523 nobody    3228 S    tinyproxy -c /mod/etc/tinyproxy.conf
 6234 root      3880 S    eth_oam -ieoam -D
 6236 root      8720 S    dpm_manager -ilan -C -D -T80 -U4 -V12 -W0 -X0
 6338 root      6664 S    /bin/avmike
 6445 root      1556 S    /sbin/chronyd -n -f /var/tmp/chrony.conf
 6607 root         0 SW   [kworker/0:2]
13459 root         0 SW   [kworker/1:1]
14953 root         0 SW   [kworker/0:0]
15024 root         0 SW   [kworker/1:0]
15192 root         0 SW   [kworker/u4:1]
17663 tor      29796 S    tor --runasdaemon 1
21525 root         0 SW   [kworker/u4:2]
22432 root      1380 S    dropbear -p 22 -0
22729 root      1408 S    dropbear -p 22 -0
22730 root      3428 S    /usr/lib/sftp-server
22736 root      1400 R    dropbear -p 22 -0
22737 root      1804 S    -sh
22864 root      1784 R    ps
</details>

Anything else I can check out for you?

**Comment by fda77** [comment]
This is broken since https://github.com/Freetz-NG/freetz-ng/commit/face6c15567047d67e623521a308679664d5b7df

**Comment by hoewer** [comment]
Works fine!
Thanx not only for caring for cosmetic problems like this one, but for your overall work on freetz, which expands even an average users opportunities by far.

**Comment by Greg57070** [comment]
Removing personalized interface name broke the possibility to connect FritzBox VoIP through WireGuard.
in voip.cfg, sipiface_tunnel only work when interface name is tun0

Is there another possibility to use sipiface_tunnel and wg0 as interface name ?

**Comment by fda77** [comment]
Ungetestet, falls es nicht klappt wird sich schon jemand melden
