### ISSUE TITLE
7590 FritzBox

### ISSUE THREAD

**Issue by webfalter** [Freetz-NG/freetz-ng#5]
ist es eigentlich korrekt das es bei obiger Box den RelaeseKernel **7583**_07.10 lädt ?

**Comment by fda77** [comment]
Ja
1) Es kann eh noch kein eigener Kernel auf der 7590 gestartet werden, steh im menuconfig bei WARNINGS
2) Nur für Kernelmodule (vermutlich hast du welche ausgewählt?) reicht meist der Sourcecode von der gleichen Kernelversion 
3) Falls 1) mal analysiert wurde (und es nötig ist) wird ein "delta patch" wie zB https://github.com/Freetz-NG/freetz-ng/blob/master/make/linux/patches/3.10.107/5491_07.01/000-7490.07.01-5491.07.01-delta.patch.xz erstellt, für verschieden Boxen braucht man dann nur 1x zu downloaden/auf die Mirror zu laden und einen kleinen Patch
