### ISSUE TITLE
lsdiff fehlt in .prerequisites

### ISSUE THREAD

**Issue by pfichtner** [Freetz-NG/freetz-ng#500]
`lsdiff`, welches von `tools/freetz_patch` benötigt wird, ist nicht in .prerequisites aufgeführt
`ERROR: freetz_patch: tool lsdiff needed for auto-fix mode, please install`

**Comment by fda77** [comment]
prerequisites ist mehr dafür gedacht was man benötigt um ein Image zu bauen (Benutzersicht). autofix wird eigentlich von fast niemandem verwendet, und so ist der Test für lsdiff im freetz_patch selbst drin.
Daher würde ich da nichts ändern

**Comment by pfichtner** [comment]
Binaries die nicht zum direkt für den build notwendig sind werden nicht in prerequisites aufgenommen.
