### ISSUE TITLE
[6660 Cable] - LAN ports do only 100 MBit/s

### ISSUE THREAD

**Issue by nextgen-networks** [Freetz-NG/freetz-ng#502]
It seems latest changes introduced after build ng-18977 (2022-03-11) and before/until 2022-03-24 created a unwanted behavior:
Box will start regularly with Ports set to max. speed (usually 1 GBit/s).
After a couple of minutes all Ports are set to 100 MBit/s mode with no possibility to change in my setup (LAN1 as WAN port).

After revert back to build ng-18977 (created 2022-03-11) everything works as expected and all Ports work in 1 GBit/s mode.

Please share your experiences. Do you face similar issues?
@dev(s): need more input?

Thanks to everyone that support this project!

**Comment by fda77** [comment]
Is this the same Fritzos version?

**Comment by nextgen-networks** [comment]
@fda77 jepp, FritzOS hast been kept with 7.29.
Only FreetzNG build has been changed.
