### ISSUE TITLE
[6660 Cable] rrdtstats cable modem 

### ISSUE THREAD

**Issue by hanneshoch3** [Freetz-NG/freetz-ng#504]
I tried to configure rrdtstats for the cable modem/docsis channels and the graph only shows NaN. I deleted the rrd file multiple times but it still doesn't show any actual data on the graph. 
![dvb](https://user-images.githubusercontent.com/102429706/160251296-730206ff-2bde-4690-986c-c37d981d326f.png)

**Comment by fda77** [comment]
This was created many Fritzos versions ago and maybe does not fit anymore. I have currenlty no cable connection nor a cable fritzbox. Additional you configuration seems not to be okay, as most cable provider are using 28 or 32 channels.
If you want to fix it: https://github.com/Freetz-NG/freetz-ng/blob/master/make/rrdstats/files/root/usr/bin/rrdstats#L212=
