### ISSUE TITLE
[6660 Cable] latest lab beta image download/make not possible

### ISSUE THREAD

**Issue by nextgen-networks** [Freetz-NG/freetz-ng#506]
Hello @fda77

saw your latest changes and wanted to give 6660 beta a try.
Changed build config with make menuconfig and started the build with "make"  and got this error:
`JUIS: Using cached value ... No cached value, asking avm for latest firmware ... no valid answer, trying backup ...
ERROR: Failed to detect the URL of the latest firmware version
make: *** [make/Makefile.image.in:146: dl/fw/6660-de_labor.detected.image] Error 3`

Any idea how to fix?

Thanks!

**Comment by fda77** [comment]
Ask AVM to update JUIS server. Meanwhile disable the detection of new versions
