### ISSUE TITLE
FritzBox 7570, remove dsld will break menuconfig immediately

### ISSUE THREAD

**Issue by MommyKnowsBest2020** [Freetz-NG/freetz-ng#507]
Hi,

I'd like to compile an image for my old 7570. At first I'd like to remove dsld, but menuconfig will break immediately, when I choose the option.

I get the following at konsole:

```
[ ] Remove dsld
ERROR: unmet direct dependencies detected for FREETZ_REMOVE_KIDS                                                                                                                                                 Depends on [n]: FREETZ_AVM_HAS_KIDS [=n] 
FREETZ_REMOVE_DSLD [=y] && FREETZ_AVM_HAS_DSLD [=y] && !FREETZ_TYPE_5140 [=n] && !FREETZ_TYPE_7112 [=n] && !FREETZ_TYPE_7113 [=n] && !FREETZ_TYPE_W501V [=n]
```

It looks like a bug for me. Years ago that was possible.

**Comment by fda77** [comment]
Years ago (tm) this was only a warning printed for such problems and freetz did something undefined.
Now its an error so users like you cant ignore it, and have to report or fix it ;-)
As this device has no KIDS, it should not be removed
