### ISSUE TITLE
wireguard.ko invalid module format on 4060 ng22040

### ISSUE THREAD

**Issue by robse-git** [Freetz-NG/freetz-ng#524]
Hello,
I compiled ng22040 for the 4060.
All fine except that I have this error now on my router when starting wireguard:
`insmod: can't insert 'wireguard.ko': invalid module format`

I also tried in ssh:
`insmod /lib/modules/4.4.60/kernel/drivers/net/wireguard/wireguard.ko`
but it gives the same error.

Some info:
```
root@fritz:/var/mod/root# uname -a
Linux fritz.box 4.4.60 #1 SMP PREEMPT 2021-10-29 armv7l GNU/Linux
```

I fetched the sources with:
`git clone https://github.com/Freetz-NG/freetz-ng ~/freetz-ng --single-branch --branch ng22040`

And compiled everything inside Freetz-Linux-2.0.0-Ubuntu (the downloadable image)

I attach the `.config` used (I did `make menuconfig; make`)

How can I solve this ?

Thank you,
Roberto
[config.txt](https://github.com/Freetz-NG/freetz-ng/files/8547031/config.txt)

**Comment by fda77** [comment]
What shows `modinfo /lib/modules/4.4.60/kernel/drivers/net/wireguard/wireguard.ko` ?
Maybe wrong sources, its up to you, see: https://freetz-ng.github.io/freetz-ng/SUPPORT.html#quellcode

**Comment by robse-git** [comment]
I don't have modinfo on the router, can you share the binary somewhere so I test ?

**Comment by fda77** [comment]
I havo no Freetz on my router

**Comment by robse-git** [comment]
> I havo no Freetz on my router

Interesting, what do you run on your router ?

**Comment by robse-git** [comment]
I think I'll return this device to Amazon as I need a working wireguard

**Comment by fda77** [comment]
Oky
