### ISSUE TITLE
haserl_0.9.35 zu haserl_0.9.36.patch

### ISSUE THREAD

**Issue by freetz-ng-mod** [Freetz-NG/freetz-ng#543]
[haserl_0.9.36.txt](https://github.com/Freetz-NG/freetz-ng/files/8783243/haserl_0.9.36.txt)
Nutze ich schon seit dem 24.08.2021

**Comment by fda77** [comment]
Hättest du dann auch 1 Jahr früher machen können...
So hatten alle ein Problem die das ins Internet freigegeben haben
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12539

**Comment by freetz-ng-mod** [comment]
Hätte ich, .......
