### ISSUE TITLE
download of rcapid-cm.tar.gz fails

### ISSUE THREAD

**Issue by michaelarlt** [Freetz-NG/freetz-ng#545]
`Download succeeded - "https://freetz.wirsind.info/rcapid-cm.tar.gz"  ->  saved to folder "dl"
Checksum mismatch for dl/rcapid-cm.tar.gz: SHA256:=e8ac61540e6984841c10ca534c6ac6fd0d889fbb95044f53f21160623f66d184 (expected: ed734e2bd98011edb561b3ee7282ab969d7552c2389661c7057960a2c241b1e5)`

for all sources where make is trying to download rcapid-cm.tar.gz it fails due to checksum mismatch. For its more or less cosmetic as i just download vie wget and its fine. Nevertheless i want you to be aware of that.

**Comment by fda77** [comment]
Seems the author changed the file without changing the filename.
The old version ed734e2bd98011edb561b3ee7282ab969d7552c2389661c7057960a2c241b1e5 is from 2003, 
the new version e8ac61540e6984841c10ca534c6ac6fd0d889fbb95044f53f21160623f66d184 from 2008

[2003 - rcapid-cm.tar.gz](https://github.com/Freetz-NG/freetz-ng/files/8787223/2003.-.rcapid-cm.tar.gz)
