### ISSUE TITLE
6890v2 Labor: Remove Leftovers geht nicht

### ISSUE THREAD

**Issue by Himan2001** [Freetz-NG/freetz-ng#558]
Ich habe soeben die Labor "96061" erfolgreich gefreezt, es gibt aber folgende Probleme:

- Remove Leftovers MUSS deaktiviert bleiben - wenn das aktiv ist wird kein LTE-Modul mehr gefunden, bzw. ist LTE broken!
- Aufgrund des riesen "Beta-files" sind nur noch 0.1 - 0.2 MB frei, Flashing ueber FREETZ funktioniert NICHT, es MUSS ueber das AVM-Webinterface geflashed werden!

Wenn ueber das Freetz Menu geflashed wird, klappt das genau einmal mit der Option "downgrade erlauben", es läuft komplett durch und geht in die "andere Bank". Wenn man dann von einem Labor auf ein anderes Labor wieder ueber Freetz Webinterface flashen will,
kommt keine "grüne OK"-Meldung mehr zurück, die Box rebootet und es steht dann in der Zielbank UNKNOWN.

Somit ist Labor-Flashing für die 6890v2 im Freetz-Webinterface BROKEN (bei randvollem image....)

STATUS-Änderung: 6890v2-LABOR: TESTED/WORKING - rennt - nur die oberen beiden Punkte beachten bzw.
die Punkte "Hidden", wenn man Labor auswählt im menuconfig.

Evtl. sollte man sich die Flashroutine im Freetz Webinterface nochmal genauer ansehen, das Problem scheint zu sein, wenn das Image nur noch wenige KB frei hat, das dann invalid geflashed wird oder zu wenig im Flash ankommt ?

Hint: beim push_firmware haben wir für dieses Modell doch 192 MB beim RAM ermittelt... tut Freetz das übers Webinterface denn auch beachten für dieses Modell ?

Das Original Image hat irgendwas bei 47 MB, das Freetz Image ganz knapp 50MB und ist am Anschlag, und sowas könnte auch
auf beiden Bänken liegen, da ist keine Luft mehr ;-)

Gegentest: 2x hintereinander via AVM-Webinterface das freetz-Labor geflasht -> Beide Bänke enthalten randvoll das gleiche Labor-Image.

Ad "inhouse": muss ich auch noch testen auf Funktion und einmal bauen und alles durchspielen ;-)

**Comment by fda77** [comment]
Hier die Hälfte der Dateien löschen, teste usw: https://github.com/Freetz-NG/freetz-ng/tree/master/patches/cond/300-remove_leftover

**Comment by Himan2001** [comment]
Lass das Ticket bitte noch etwas offen, ich brauch dafür ein paar Tage mehr, da ich angefangen habe mit der 6890v2 mal produktiv zu arbeiten und ich habe aktuell die 7.29 final drauf und sehe da in der shell mit aktivem WLAN recht viele kernel-oops und segfaults, kann bislang aber noch nicht einwandfrei erkennen wodurch die entstehen. Ich muss das in Zusammenhang mit der Verwendung des letzten Labors dann auch noch vergleichen und etwas länger laufen lassen.

Ich habe bei der 7.29 die Leftovers aktuell entfernt, bei der Labor nicht.

Was mir bisher aufgefallen ist, das bei Änderungen und Umschaltungen der WAN-Wege, also zwischen DSL/WAN + Mobilfunk, bzw. der laufenden config der möglichen Anbindungen, das (USB) angebundene Modem "vom Bus" fliegt, und nach einer Weile wieder "kalt" initialisiert wird.

Seit 20 Stunden habe ich die Box jetzt LTE-only mit deaktivem WLAN mal durchlaufen und bislang kein einziger Segfault, so kann ich mich dann besser an das eigentliche Problem herantasten.

Was aber im laufenden Betrieb gerne passiert ist, das wenn man DSL/WAN zwischenzeitlich ein oder ausschaltet, umkonfiguriert usw, das kurz nach dem "übernehmen" der Einstellungen die Box direkt nach einem segfault dann einfach rebootet.

Nach dem Kaltstart und dem ueblichen Init aller vorherigen config-Einstellungen habe ich dann auch so 2-3 segfaults im dmesg bis alles fertig initialisiert wurde. Das ist bei mir erst dann weggewesen, nachdem ich WLAN komplett abgeschaltet hatte.

Problem dabei: WLAN funktioniert in der Final und Labor aber einwandfrei. Somit muss ich das mit serieller Schnittstelle
und original Image von AVM auch noch mal vergleichen.

Und last but not least steht im Changelog zur Labor bei der 6890 auch noch ne lange Liste von Behebungen drin, wie z.b. init-Probleme des LTE-Modems behoben () und "WLAN"-Funktionen verbessert usw. gefixt.



> Hier die Hälfte der Dateien löschen, testen usw: https://github.com/Freetz-NG/freetz-ng/tree/master/patches/cond/300-remove_leftover

Den Teil gehe ich daher etwas strukturierter an und mach mal ein Ausschlussverfahren. Wir haben dann ja auch noch eine neuere Busybox-Version als AVM selber verwendet - somit muss ich auch hier genauer hinsehen und config-Vorgänge nachvollziehen können im Vergleich....


@all: Sind hier noch andere Nutzer die eine 6890v1 oder v2 einsetzen und haben praktische Erfahrungen sammeln können im laufenden Betrieb oder kann noch jemand Anderes bestätigen das es gewisse Auffälligkeiten bei der config gibt und zwischenzeitliche reboots / WLAN-Init-Probleme ?

Aufgrund "Speichermangels" in den Labors sind MyFreetz & TR069 entfernt worden (Option Hardening ON),
wenn ich das mit reinnehme, muss SNMP und einige extra Tools alles wieder rausfliegen, weil einfach kein Platz mehr ist.
max. 50 MB ist das Image-Limit (leider).

**Comment by fda77** [comment]
Jeden Tag kommt ne neue Labor/Inhaus, mal geht sie, mal nicht. Und was geändert wurde weiss sowieso niemand.
Wie wäre es denn hier mit den Diskussionen für Erfahrungsberichte etc: https://github.com/Freetz-NG/freetz-ng/discussions
