### ISSUE TITLE
Die 6591 07.39-97972 hat ein neuen oder anders gesagt ein anderen Kernel

### ISSUE THREAD

**Issue by freetz-ng-mod** [Freetz-NG/freetz-ng#581]
FRITZ.Box_6591_Cable-07.39-97972-LabBETA.image
    ... used by AVM ...... 4.9.279
    ... used by Freetz ... 4.9.250
ERROR: Freetz and AVM kernel versions do not match. Wrong kernel version configuration in Freetz?

**Comment by fda77** [comment]
Wo die kleinen Sourcepakete herkommen weisst du ja..
Da nur die Docsis Dinger von avm x86/atom haben wird es noch nichts nutzbares geben.
Bevor dur fragst: Ich hab extra nochmal die komplette GPL gelesen, da gibt es KEINEN  Abschnitt "Für eine Labor von AVM braucht kein Sourcecode herausgerückt zu werden"!

**Comment by freetz-ng-mod** [comment]
Ich könnte auch auf Klo gehen, ;-) man könnte vieles

**Comment by fda77** [comment]
Damit du DAVOR auch das Hösschen runterziehst hab ich deinen Betrag gelikt

**Comment by fda77** [comment]
Du könntest aber heraussuchen was von 6591 + 6660 die letzten revisionen mit der alten Kernelversion waren

**Comment by fda77** [comment]
> die letzten revisionen mit der alten Kernelversion waren

**Comment by freetz-ng-mod** [comment]
FRITZ.Box_6591_Cable-07.39-97061-LabBETA.image

**Comment by fda77** [comment]
Dies c85bad2e5e387f19c238631b9429e518d4bb002e ?

**Comment by fda77** [comment]
Schau am besten selbst durch: https://github.com/Freetz-NG/freetz-ng/commits/master/docs/JUIS.md

**Comment by fda77** [comment]
Also, schreib avm ne mail, dann -> https://github.com/Freetz-NG/freetz-ng/discussions/134
