### ISSUE TITLE
Fehler: Datei 'crt' des Pakets 'lighttpd' ist unbekannt.

### ISSUE THREAD

**Issue by hannsen** [Freetz-NG/freetz-ng#614]
Wenn man in der [lighttpd Konfiguration](http://fritz.box:81/cgi-bin/conf/lighttpd) auf "_Damit lighttpd mit SSL-Unterstützung gestartet werden kann, müssen Zertifikat & Schlüssel [hier](http://fritz.box:81/cgi-bin/file/lighttpd/crt) eingetragen sein._" klickt kommt die Meldung "Fehler: Datei 'crt' des Pakets 'lighttpd' ist unbekannt." und man kann somit kein SSL konfigurieren.

## Fehler 
![error](https://user-images.githubusercontent.com/3775136/190862331-191a7ff2-ecf8-4366-bf28-4480d7f20cd0.PNG)

## Lighttpd Config

![config lighttpd](https://user-images.githubusercontent.com/3775136/190862332-04db49c6-7904-4c8c-aec6-d637208b5c1d.png)

## Freetz Config

[config.txt](https://github.com/Freetz-NG/freetz-ng/files/9591918/config.txt)

**Comment by hannsen** [comment]
```
server.modules += ( "mod_openssl" )
$SERVER["socket"] == ":443" {
  ssl.engine = "enable" 
  ssl.pemfile = "/var/www/htdocs/etc/lighttpd.pem" 
}
```

Ich habs jetzt auch so versucht, aber dann meckert es, dass es kein mod_openssl.so gibt.

Wie konfiguriere ich denn SSL für lighttpd?

**Comment by hannsen** [comment]
Hab jetzt diese Zeilen in `/make/lighttpd/Config.in` hinzugefügt und nochmal ein Image erstellt, damit scheint es zu gehen:
```
   	config FREETZ_PACKAGE_LIGHTTPD_MOD_OPENSSL
           	bool "mod_openssl"
          	default y
           	help
                   	This option adds mod_openssl.so to the image.
```

**Comment by fda77** [comment]
Sollte nun funktionieren, keines der 3 möglichen ssl-Module wurde wegen falschem Symbolnamen mit ins Image kopiert.
