### ISSUE TITLE
dehydrated braucht Openssl EC Support

### ISSUE THREAD

**Issue by hannsen** [Freetz-NG/freetz-ng#618]
Damit dehydrated läuft braucht das Openssl Package ec support, das sollte dann automatisch angestellt werden wenn man dehydrated nutzt.
Momentan muss man es im Expertenmodus bei shared libraries manuell anschalten.

Ich denke es ist diese Option `FREETZ_LIB_libcrypto_WITH_EC=y`

**Comment by fda77** [comment]
Die EC haben schon öfter mal bei anderen Packages gefehlt, um sie immer mit openssl einzuschalten brauchen sie aber ein bisschen zu viel Platz

```
Nix
1.828.696  /usr/lib/freetz/libcrypto.so.1.1
  433.696  /usr/lib/freetz/libssl.so.1.1
  552.980  /usr/bin/openssl


EC
2.168.776  /usr/lib/freetz/libcrypto.so.1.1
  458.504  /usr/lib/freetz/libssl.so.1.1
  578.420  /usr/bin/openssl
```
