### ISSUE TITLE
modpatch: Error in patch-file `make/linux/patches/3.10.107/551-missing_netfilter_includes.upstream.patch`

### ISSUE THREAD

**Issue by vogler** [Freetz-NG/freetz-ng#620]
Ich habe versucht die Firmware im pfichtner-freetz Docker image zu bauen, aber bei der Anwendung eines Patches hat es dann abgebrochen: 

```console
builduser@d5d40f69764a:~$ make
Freetz-NG 20243M-c50401dbe master 2022-09-27
...
    patching file linux-3.10/include/uapi/linux/netfilter/xt_RATEEST.h
    Hunk #1 succeeded at 2 with fuzz 2.
    patching file linux-3.10/include/uapi/linux/netfilter/xt_TEE.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_TPROXY.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_hashlimit.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_ipvs.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_mac.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_osf.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_physdev.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_policy.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_rateest.h
    Hunk #1 FAILED at 2.
    1 out of 1 hunk FAILED -- saving rejects to file linux-3.10/include/uapi/linux/netfilter/xt_rateest.h.rej
    patching file linux-3.10/include/uapi/linux/netfilter/xt_recent.h
    patching file linux-3.10/include/uapi/linux/netfilter/xt_sctp.h
    patching file linux-3.10/include/uapi/linux/netfilter_arp/arp_tables.h
    patching file linux-3.10/include/uapi/linux/netfilter_bridge.h
    patching file linux-3.10/include/uapi/linux/netfilter_bridge/ebt_arp.h
    patching file linux-3.10/include/uapi/linux/netfilter_bridge/ebt_arpreply.h
    patching file linux-3.10/include/uapi/linux/netfilter_bridge/ebt_ip6.h
    patching file linux-3.10/include/uapi/linux/netfilter_bridge/ebt_nat.h
    patching file linux-3.10/include/uapi/linux/netfilter_ipv4/ip_tables.h
    patching file linux-3.10/include/uapi/linux/netfilter_ipv6/ip6_tables.h
    patching file linux-3.10/include/uapi/linux/netfilter_ipv6/ip6t_rt.h
ERROR: modpatch: Error in patch-file make/linux/patches/3.10.107/551-missing_netfilter_includes.upstream.patch
make[1]: *** [make/linux/kernel.mk:74: source/kernel/ref-vr9-7490_07.27/.unpacked] Error 2
make: *** [Makefile:46: envira] Terminated
```

Das ist der Patch:
https://github.com/Freetz-NG/freetz-ng/blob/342950c57174e60d24f909dcf821154cd07c1e82/make/linux/patches/3.10.107/551-missing_netfilter_includes.upstream.patch#L1-L7

Host hat eine M1 CPU. Angeblich kann qemu nicht alles emulieren, aber das scheint mir nicht das Problem zu sein:
```console
builduser@d5d40f69764a:~$ uname -a
Linux d5d40f69764a 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
builduser@d5d40f69764a:~$ make
Freetz-NG 20243M-c50401dbe master 2022-09-27
You have no CPU with AVX2 support, precompiled (download) host-tools automatically disabled.
Makefile:259: *** Please re-run.  Stop.
make: *** [Makefile:46: envira] Terminated
builduser@d5d40f69764a:~$ make
Freetz-NG 20243M-c50401dbe master 2022-09-27
JUIS: Using cached value ... No cached value, asking avm for latest firmware ... http://download.avm.de/fritzbox/fritzbox-7430/deutschland/fritz.os/FRITZ.Box_7430-07.29.image ... done.
...
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
...
-- Performing Test HAVE_ASM_AVX2
-- Performing Test HAVE_ASM_AVX2 - Success
-- Performing Test HAVE_ASM_AVX512
-- Performing Test HAVE_ASM_AVX512 - Success
```

[config.txt](https://github.com/Freetz-NG/freetz-ng/files/9664825/config.txt)

**Comment by vogler** [comment]
Ok, ich sehe gerade dass der patch `xt_rateest.h` und `xt_RATEEST.h` enthält, ich aber nur `xt_rateest.h` habe.
https://github.com/pfichtner/pfichtner-freetz#how-to-use-it empfielt das repo zu mounten - auf macOS mit default case-insensitive file system ist das keine gute Idee...
Ich probiere es jetzt nochmal ohne mount.

**Comment by pfichtner** [comment]
Den mount empfehle ich, damit das Repo im Filesystem des Host-Systems liegt und nicht im Container, was den Vorteil hat, dass man den Container wegwerfen kann ohne Build-/Zwischenartefakte zu verlieren.

**Comment by pfichtner** [comment]
@vogler  Ich habe die Anleitung noch um "volumes" ergänzt, bei welchem Du nicht vom Dateisystem des Hosts abhängst und trotzdem den Build-Image-Container verwerfen kannst. Vielleicht ist das sogar die bessere default Variante für mein README/how-to-use.

**Comment by vogler** [comment]
@pfichtner ~~Ja, verständlich. Am besten in der Readme noch erwähnen dass macOS und Windows standardmäßig case-insensitive sind, weshalb man auf diesen Systemen entweder ein extra case-sensitive Volume mounten oder direkt im Container arbeiten muss, ansonsten schlägt `make` irgendwann fehl.~~
Passt, evtl. noch erwähnen: The used volume needs to be a case-sensitive file system.

**Comment by vogler** [comment]
Das issue ist somit vsl. geklärt.
Es baut leider immer noch. Wie lange dauert ein Build normal?
Rosetta hat normal nicht besonders viel Overhead, aber wsl. ist qemu hier sehr langsam.

**Comment by pfichtner** [comment]
> Es baut leider immer noch. Wie lange dauert ein Build normal?

Kommt auf die Pakete/Anzahl Pakete an, bei mir je nach Box und Paketen zwischen 30 und 60 Minute from scratch.

**Comment by vogler** [comment]
Danke. Ist jetzt fertig und hat ~6h gedauert. Als zusätzliche Pakete hatte ich nur dnsmasq, htop, tmux.

**Comment by pfichtner** [comment]
> Danke. Ist jetzt fertig und hat ~6h gedauert. Als zusätzliche Pakete hatte ich nur dnsmasq, htop, tmux.

Das ist extrem lang und sicherlich der Prozessoremulation geschuldet.
