### ISSUE TITLE
Fritz Repeater 1200

### ISSUE THREAD

**Issue by nd570** [Freetz-NG/freetz-ng#630]
Fritz Repeater 1200 not working for me.

tools\push_firware ends with errors - ftp write errors after nearly 99% - "stalled"
tools\image2inmemory and then .\EVA-FTP-Client.ps1 on windows failed also
avm recover works.

push_firmware needs a second power cycle to start ftp transfer, terminal output is attached below.

**_`BTW/FYI: I can report Fritz Repeater 2400 works! (menuconfig asks for feedback.)`_**

(menu)config not changed from defaults!

<<<<< terminal output push_firmware >>>>>>>>>>>>>>>>>>>>>>>>>
tools/push_firmware

 * Analyzing 'images/1200_07.29.all_freetz-ng-20295M-2373462f9_20221008-210546.image' ...
 * Product: Fritz_Box_HW244 (FRITZ!Repeater 1200)
 * Using command: ftp
 * Target host: 192.168.178.1
 * Outgoing IP: 192.168.178.168
 * Flash mode: ram-boot
 * Allowed memory size: 128 MB
 * Designated linux_fs_start: <other>

 !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!
 !!!  THERE IS NO WARRANTY AT ALL !!! USE AT YOUR OWN RISK   !!!

 * Are you sure, that you want to flash this file to the device?
   images/1200_07.29.all_freetz-ng-20295M-2373462f9_20221008-210546.image
   Proceed? (y/[n]) y

 * You should now reboot your box (192.168.178.1). Waiting for shut down.
   Switch off, if reboot is not detected because it happens too quickly.
   Some newer bootloader versions allow to flash on power-cycle only.

 * MAPSTART=0x80000000
 * FULLSIZE=0x08000000   (128 MB)
 * MAPLIMIT=0x88000000
 * FILESIZE=0x01089800   (~16 MB)
 * ALIBYTES=0x00000000   (~0 kB)
 * FREESIZE=0x06f76800   (~111 MB)
 * MTDSTART=0x86f76800

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting ............. found!

 * Detected linux_fs_start: '0'
 * Designated linux_fs_start: 1

 * No reply from box, assuming switch-off or restart. Trying to re-detect box.
   Waiting ............... found!

 * Box is back up again, initiating transfer.

Connected to 192.168.178.1.
220 ADAM2 FTP Server ready
331 Password required for adam2
230 User adam2 successfully logged in
Remote system type is AVM.
Debugging on (debug=1).
---> TYPE I
200 Type set to BINARY
---> MEDIA SDRAM
200 Media set to MEDIA_SDRAM
---> SETENV memsize 0x06f76800
200 SETENV command successful
---> SETENV kernel_args_tmp mtdram1=0x86f76800,0x88000000
200 SETENV command successful
local: /tmp/freetz_Lbj/ramboot.flash remote: 0x86f76800 0x88000000
ftp: setsockopt SO_DEBUG (ignored): Permission denied
---> EPSV
502 Command not implemented
disabling epsv4 for this connection
---> PASV
227 Entering Passive Mode (192,168,178,1,115,253)
---> STOR 0x86f76800 0x88000000
150 Opening BINARY data connection
 99% |************************************************************************** | 16848 KiB  886.70 KiB/s  - stalled -ftp: Writing to network: Connection reset by peer
  0% |                                                                           |    -1        0.00 KiB/s    --:-- ETA

**Comment by fda77** [comment]
I've changed the default value for push firmware.
The other scipt/tool EVA-FTP-Client.ps1 is not a part of freetz and has its own repo by @PeterPawn!
