### ISSUE TITLE
[external] external file is not created

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#635]
version: latest build with clean checkout
host: ubuntu 20 lts

have loaded my config (last build on 4.10.2022) but the external file (usb.ids) will not created.

[b.config.txt](https://github.com/Freetz-NG/freetz-ng/files/9932890/b.config.txt)

**Comment by aus-sua** [comment]
Ich hänge mich hier einmal mit an,
ich denke "mein" Problem ist auch sein Problem.
---> Es werden keine Externals-Files erstellt.

Ich denke, bei meiner 7390 sieht man genauer, wo das Problem liegt.

Hier, ein BC wo es (auch) noch funktioniert 
![external_i O _](https://user-images.githubusercontent.com/73757472/200132376-296f543c-76da-481b-b1c3-9ec219d26e94.jpg)

und hier eine BS mit den fehlenden externals 
![external_def_](https://user-images.githubusercontent.com/73757472/200132102-85773919-792b-4465-960a-ba074d9aeb11.jpg)

Das Problem ist wohl mit den Änderung der Pfade (z.B. make: fix some links....) zwischen:
feb2cd728d9f7 (das entspricht dem letzte Tag [ng22100], damit funktioniertes noch)
und z.B.
20d577d8b53 (das ist gleich nach den Pfadänderungen, damit tritt das Problem auf)
entstanden.
Da greift wohl ein script noch auf die älteren Pfadangaben zu und findet damit wohl
die separierbaren externals nicht (mehr)?

Hier noch das cmake-File (als zip) dazu
[cmake.log_18.10._20d577d8b5_v.06.87-old__.zip](https://github.com/Freetz-NG/freetz-ng/files/9944352/cmake.log_18.10._20d577d8b5_v.06.87-old__.zip)

**Comment by fda77** [comment]
Ja, das Problem kam vom Verschieben in make/ . Bitte testen, ich geh davon dass das alles war
Es ist durchaus möglich dass noch die eine oder andere Stelle gefunden wird die übersehen wurde

**Comment by aus-sua** [comment]
Bei mir passt es damit da jetzt wieder, echt Knorke  ;-)

Vielen Dank für den schnellen Fix!
:+1:

**Comment by harryboo** [comment]
Funktioniert wieder, Danke...

**Comment by fda77** [comment]
Danke für die Rückemeldungen!
