### ISSUE TITLE
Package Minisatip: Segmentation fault

### ISSUE THREAD

**Issue by fre73** [Freetz-NG/freetz-ng#643]
Hello,

after compiling freetz-ng for my FritzBox 6490 Cable with main branch I keep getting "Segmentation fault" Error trying to run minisatip.
In my old Issue #631 about compiling error, cause of patch, I also uploaded my configurations and core dump.
Compilation is now fixed, but this error persists.

Any Advice?
Maybe Bump minisatip version?

Tnanks @fda77 for your hard work :)

**Comment by fda77** [comment]
Yes, check with strace when it crashes, but the longer version:
`strace -fff minisatip -f -l http`
My guess: something with avm's kernel-config,
Hard work would be a bump to newest version ;-)

**Comment by fre73** [comment]
Thanks, I didn't know that it will be so difficult to run non avm Sat2IP Server on Fritzbox.
I think I will stick with another solution with Raspberry Pi and DVB-C USB Stick..

If u want I can deliver the strace, but I will now stick with my new solution :)

**Comment by fda77** [comment]
Everyting is possible, avm uses sometime custim (dvb) hardware with kernelpatches or whatever...
But to fix a problem you first need to know what the problem is
