### ISSUE TITLE
Paket PPP läßt sich nicht einbinden

### ISSUE THREAD

**Issue by karstengit** [Freetz-NG/freetz-ng#655]
Für das Paket PPP endet die Kompilierung mit:

```
WARNING: File of kernel module not found: ppp_async.ko
WARNING: File of kernel module not found: ppp_deflate.ko
WARNING: File of kernel module not found: ppp_generic.ko
WARNING: File of kernel module not found: ppp_mppe_mppc.ko
WARNING: File of kernel module not found: sha1_generic.ko
WARNING: File of kernel module not found: slhc.ko
ERROR: Enable missing with 'make kernel-menuconfig' as (M)odule (and push a pull request). Use '/' to search in menuconfig.
```
ohne das ein Image erstellt wird.

Die entsprechenden Kernelmodule sind jedoch in der Konfiguration bereits ausgewählt:

![ppp 1](https://user-images.githubusercontent.com/5941550/205493138-19273e7b-b91a-4c23-8c35-64dea90aa374.jpg)

![ppp 2](https://user-images.githubusercontent.com/5941550/205493141-8925bf1f-e723-455d-8d8a-cd2f0741187c.jpg)

Das einzige Kernel-Modul was in der Auflistung komplett fehlt und daher nicht ausgewählt werden kann ist **sha1_generic.ko**

Was muß getan werden?

**Comment by karstengit** [comment]
Hier ist die dazugehörige .config
[config.zip](https://github.com/Freetz-NG/freetz-ng/files/10148594/config.zip)

**Comment by fda77** [comment]
Dein gepostetes Lesen -> machen

**Comment by karstengit** [comment]
Keine Ahnung - ein sha1_generic.ko läßt sich schwer erfinden.
Das Modul PPP ist mandantory und somit läßt sich ein Image für diese Box offensichtlich nicht kompilieren!

**Comment by karstengit** [comment]
Der beschriebene Fehler mit den fehlenden Kernel-Modulen tritt ganz klar auf, wenn PPP unter den Weboberflächen aktiviert wird.

Wenn das Mal kein Bug ist ...

**Comment by fda77** [comment]
Ganz klar kannst du nicht lesen
