### ISSUE TITLE
7590 7.20: Davfs2 Webkonfiguration funktioniert nicht

### ISSUE THREAD

**Issue by forenuser** [Freetz-NG/freetz-ng#67]
Die Webkonfiguration von Davfs2 scheint nicht zu funktionieren.

Manuelles Mounten funktioniert mit dem folgenden Befehl problemlos:
`mount.davfs https://webdav.smartdrive.web.de /tmp/test/myDAV
`

Allerdings müssen der Benutzer davfs2 und das Verzeichnis /var/cache vorher manuell angelegt werden!

**Comment by fda77** [comment]
Du könntest versuchen ob ein Aufruf von "config" in load) in https://github.com/Freetz-NG/freetz-ng/blob/master/make/davfs2/files/root/etc/init.d/rc.davfs2 bewirkt was du möchtest
Es bietet sich übrigens an autofs für cifs,davfs und samba zu verwenden. die 7590 hat das sogar scheinbar im kernel drin

**Comment by forenuser** [comment]
In der Webkonfiguration gibt es 4 Konten. Bei Konto 0 wird versucht, die Daten zu übernehmen, welche in der AVM Konfiguration hinterlegt sind. Beim Benutzernamen und Passwort funktioniert dies nicht (mehr). Bei den folgenden Konten soll ein Serverkey hinterlegt werden - eigentlich der Key der Zertifizierungsstelle. Dieser wird scheinbar nicht akzeptiert, weil dieser Key nicht verifiziert werden kann.

**Comment by fda77** [comment]
Entweder jemand fixt dieses avm-konto0 oder es wird einfach deaktiviert
Fehlt dir vielleicht einfach ein intermediate-Zertifikat? Das kommt öfter vor.
Wäre aber noch besser wenn man das ca-bundle package dazu verwenden könnte, dann muss man mit dem Zertifikat nur was machen wenn es ein selbst signiertes ist

**Comment by forenuser** [comment]
Bei Konto 1 hat es nun mit dem T-TeleSec GlobalRoot Class 2 Zertifikat funktioniert. In /mod/etc/ssl/certs/ca-bundle.crt scheint das erforderliche Zertifikat nicht enthalten zu sein.

**Comment by fda77** [comment]
Wenn du ohne Warnmeldung mit dem Browser auf die webdav Adresse zugreifen kannst, sollte es im ca-bundle drin sein

**Comment by fda77** [comment]
Aber fang doch mit einer aktuellen Version an: http://mirror.netcologne.de/savannah/davfs2/
Die in freetz ist 6 Jahre älter als die neueste

**Comment by forenuser** [comment]
Zuerst kommen die wichtigeren Themen ;-)

**Comment by fda77** [comment]
0d3686e6ceedf5c296f3537129fbfce52a534129 bump lib-neon
e827e01e3dcde21bdfdd71c3e97dad24c8464ed3 bump davfs2
bf5b397e79c48763685bcc53ec499ce3eb3ee270 davfs2: add new patches
3fe177df563fc3dd3b9044d92456e6a7b706cf04 davfs2: move old patches

**Comment by fda77** [comment]
geht nun mit autofs auf 7490

 847a823cf ca-bundle: fix davfs2
 d675b829d autofs: fix davfs2
 02cace68b davfs2: add ca-bundle suboption
