### ISSUE TITLE
5590 kdsld wird nicht geladen/gestartet (log-flooding im syslog/freetz-log)

### ISSUE THREAD

**Issue by maverick3005** [Freetz-NG/freetz-ng#675]
Bei der 5590 ist mir aufgefallen das kontinuierlich versucht wird den kdsld zu starten, welcher jedoch immer down bleibt.
Evtl. hat das etwas mit DHCP und dem ISP zu tun, und kdsld kommt evtl. nur bei pppoe zum Einsatz ?

Freetz zeigt in den Logfiles kontiuierlich Fehler an, das der kdsld nicht gestartet werden kann, sofern eine entsprechende
dhcp condig zum ISP vorhanden ist (also kein PPPoE & co in Verwendung ist...) wäre es evtl. hilfreich die unentwegten Neustart-Versuche zu unterbinden. Die Originalfirmware versucht den kdsld in Abhängigkeit der ar7.cfg Config ebenfalls nicht dauerhaft neuzustarten.

**Comment by fda77** [comment]
> Freetz zeigt in den Logfiles kontiuierlich Fehler

Und die soll ich mir aus dem Hintern ziehen?
