### ISSUE TITLE
FRITZ!Repeater 3000 sources

### ISSUE THREAD

**Issue by MasterRoCcO** [Freetz-NG/freetz-ng#68]
https://osp.avm.de/fritzwlan/fritzrepeater-3000/sources-files_FRITZ_Repeater_3000-7.20.tar.gz

**Comment by fda77** [comment]
Danke werden aber nicht gebraucht. Höchstens wenn jemand was nachschauen oder replace kernel nutzen möchte 
Es werden die 7.20 sourcen vom 1200 genutzt der die gleich kernelversion 4.4 und cpu IPQ40xx hat. 
https://github.com/Freetz-NG/freetz-ng/blob/master/config/avm/source.in#L316
