### ISSUE TITLE
Load config (7390) is not possible anymore

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#72]
The attached config cannot be loaded.
[config.txt](https://github.com/Freetz-NG/freetz-ng/files/5212625/config.txt)

**Comment by harryboo** [comment]
Hi,
sorry goes again after newly checked out. No idea what was going on.
Thanx

**Comment by fda77** [comment]
That means "fixed" :)
Many kernel-module parts of Freetz are not 100% correct...
