### ISSUE TITLE
LabBeta 5590 / push_firmware issue

### ISSUE THREAD

**Issue by maverick3005** [Freetz-NG/freetz-ng#744]
Nach einem erfolgreichen testcompile und dem Versuch das erstellte image einzupielen kam jetzt das:

```
 ./push_firmware 5590_07.39.all-rev102864_labor_freetz-ng-21297-a1ddabda1_20230223-014300.image

 * Analyzing '5590_07.39.all-rev102864_labor_freetz-ng-21297-a1ddabda1_20230223-014300.image' ...
Error: it is not known how to flash a fit-boot image with 'rootfs_ram' method yet.
Error: run a recovery.exe and get a capture by wireguard or tcpdump to add it.
Error: meanwhile install an older firmware and flash this one by the web interface.

Ein Gegentest mit der stable FOS 7.30 ergibt hingegen:

./push_firmware 5590_07.30.all_freetz-ng-21278-3def93864_20230220-222041.image

 * Analyzing '5590_07.30.all_freetz-ng-21278-3def93864_20230220-222041.image' ...
 * Product: Fritz_Box_HW272 (FRITZ!Box 5590)
 * Using command: ftp
 * Target host: 192.168.178.1
 * Outgoing IP: 192.168.178.2
 * Flash mode: fit-boot
 * Allowed memory size: 1024 MB
 * Designated linux_fs_start: <other>

 !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!
 !!!  THERE IS NO WARRANTY AT ALL !!! USE AT YOUR OWN RISK   !!!

 * Are you sure, that you want to flash this file to the device?
   5590_07.30.all_freetz-ng-21278-3def93864_20230220-222041.image
   Proceed? (y/[n])


```
Einzig ist das Beta-Image mit 62 MB einiges grösser, da ja noch urloader UND tzupdate binarys jetzt zusätztlich drin sind.

Irgendwelche Ideen ? abgesehen von ggfs. manuellen push-firmware ram -switches, bzw. sowieso flaschen über
das Webinterface im Freetz ? - push_firmware sollte ja künftig eine 5590 FOS 7.50 auch im ersten Anlauf, samt
der update-binarys, initial Flashen können ;-)

Für die Final 7.50 sollte da wohl das RAM-Limit angepasst werden, da mit Sicherheit hier ebenfalls die beiden
extra urloader + tzupdate binarys mit drin sein werden. Kleiner wirds seitens AVM erst mal nicht.

So wie ich das mitbekommen habe ist für den Fiber-Teil/GPON künftig bei Updates auch häufiger ein anpassen
des Urloaders & trustzone Teil des Firmware-Updates, da Teile der "Blackbox" direkt (signiert) jetzt in diesen
Bereichen liegen. Ich vermute das "OLT-Verheiratungen/AES-Keys", usw. wohl dort "geschützt" abgelegt werden ?

**Comment by fda77** [comment]
![image](https://user-images.githubusercontent.com/471850/220921178-3a24560e-81ff-4729-aace-7586c68b0e72.png)

**Comment by fda77** [comment]
Lass diesen ganzen urlader und trustzone kram einfach wie er ist

Wie kommt man eigentlich auf die [] Idee die AVM Dienste ohne Grund zu beenden? Ich hab die Optionen entfernt

**Comment by fda77** [comment]
es gibt zu viele 5590 issues/diskussionen, ich mache diese mal zu
