### ISSUE TITLE
Freetz Firmware Update broken für 7490 (ggfs. auch andere Modelle) + frisches Labor 7.51

### ISSUE THREAD

**Issue by maverick3005** [Freetz-NG/freetz-ng#749]
Ich habe heute mal die aktuelle Firmware "fritzbox-7490-labor-103578.zip" in den entsprechenden 2 config-Files eingetragen.
(Kernel ist wie immer gleich geblieben) und auch erfolgreich gebaut:

Nach Deinen letzten Fixxes für das Freetz-Flashing passiert jetzt das (Browserunabhängig):

![update1](https://user-images.githubusercontent.com/119104833/221958282-9deb409b-7f42-4548-b27e-53ec5ebab75a.png)
![update2](https://user-images.githubusercontent.com/119104833/221958286-e2e823bd-717f-4a15-ac93-35b798d3381d.png)
![update3](https://user-images.githubusercontent.com/119104833/221958289-78eec963-c3ac-49b6-9a53-f1cdcb494fdb.png)

Der gewünschte zu flashende Filename war in diesem Fall:
"7490_07.51.all-rev103578_labor_freetz-ng-21312M-682db066b_20230228-043534.image"

Siehe Bild 3 -  es erscheint nur noch "Keine Firmware hochgeladen"...

Workaround: Ab jetzt mit dem AVM-WebIF flashen übergangsweise und hoffentlich alle Certs auch mit im Image drin,
und im Freetz WebIF dann ggfs. die Bootbank nochmal manuell umschalten.

Fall Du es updaten möchtest im Trunk für die 7490:

Die frischen Filenamen:
fritzbox-7490-labor-103578.zip
sowie
FRITZ.Box_7490-07.51-103578-Labor.image

weitere Änderungen sind nicht erforderlich wie ich das ersehen konnte.

Zur 5590 gibts auch ein Update:
fritzbox-5590-fiber-labor-103612.zip
sowie:
FRITZ.Box_5590_Fiber-07.39-103612-LabBETA.image

Auch hier: keine weiteren Änderungen nötig, der Rest bleibt gleich.
Könnte gerne direkt zusammen mit den 7490er Filename-Änderungen mitgemacht werden.

Bitte erst einmal NACHVOLLZIEHEN und dann erst Ticket closen ;-) - Daaaanke.

Extra Hinweise: Kein Werksreset oder recovery zwichen den Schritten. Ich bin direkt von der letzten 7490/Lab auf die aktuelle gegangen über Freetz, danach gibt es nur noch die 1. Option und die Haken-Option "downgrade" - wobei auch das zum selben Ergebnis führt, es wurde keine Firmware hochgeladen. (Firefox & Chrome identisch). Bei der 5590 hingegen hat es über das WebIF
problemlos noch hingehaun "zweimal" dassselbe neue Labor zu flashen (da waren die Menüpunkte noch vorhanden, und
"In memory - ohne Dienste anhalten" lief problemlos von Old Lab auf New Lab durch.

(und ja: Natürlich habe ich auch ein "Browser-Cache Cleaning" vorweg noch gemacht zur Sicherheit)

**Comment by fda77** [comment]
Muss das um DIESE UHRZEIT SO VIEL WEISS SEIN?
Du kannst gern PRs machen, mir sind die versionen egal

**Comment by fda77** [comment]
Jo, javascript verhält sich nicht wie erwartet.
Bitte keine Patcher, sonder gleich als PR. Ihr wolltet doch alle Git...
