### ISSUE TITLE
LAB-Updates patch für 5590 + 6890 - Bitte um revice / Probleme mit "Flash-Image zur gross" bei der 6890 jetzt

### ISSUE THREAD

**Issue by maverick3005** [Freetz-NG/freetz-ng#756]
Hallo.

Nach einem ausführlichem Lokaltest hier ein generischer Patch zum Update der Labore für die 5590 und 6890
mit der Bitte um eine letzte Prüfung.

Fix:
[labor-updates2.patch](https://github.com/Freetz-NG/freetz-ng/files/10890605/labor-updates2.patch)

Da bei der 6890, bei der auf die AVM-Diffs der 7590 zugegriffen wird, muss noch eine exklusion für den neuen Kernel 4.9.235
gesetzt weden, da es hier noch keine AVM-diff gibt im Moment. Somit erst einmal Vanilla hier.

Hinweis/Request:

bei der 6890 ist das Image jetzt zu gross!

Die Revision hat jetzt auch einen Sprung von 7.39 -> 7.51 gemacht intern bei AVM.

Es kann gerade einmal der MC noch eingebaut werden und tr69 entfernt werden, ferner muss Myfritz rausfliegen.
Dann sind im Image gerade noch 23000 Bytes frei. Extra Tools... keine Chance mehr....

Vorschlag für eine weitere "Removing"-Option, ggfs. auch sinnvoll für die anderen LTE-Modelle (im Labor+Finals):

Es sind neben der abwählbaren 2. DSL-Firmware (also die "Vorgängerversion")
Jetzt auch 2 LTE Firmwares als Binary-Blobs mit in der Firmware. Diese Binarys belegen fast 2 MB extra Platz und ein
vollständiges Image für Leute die tr69 und MyFritz weiter drin haben wollen lässt sich wg. Speichermangel nicht mehr bauen.

Dazu gibt es im LTE-Bereich des Webinterfaces, so wie bei DSL die Option "Downgrade" auf Vorgängerversion für das
(USB)-LTE-Modul.

Wenn im Image nur noch die aktuellere LTE-Firmware enthalten ist, erfolgt automatisch direkt nach dem ersten Flashen dann
einmalig ein Firmware-Update des USB-Moduls, welches auch im Logfile protokolliert wird beim ersten Neustart.

@fda77 
Könntest Du ggfs. die Sektion "Remove-Patches" erweitern für die LTE-Modelle das man eine 2. LTE-Firmware (also Downgrade)
der Binarys als auch die WebIF Funktion entfernen kannst - so wie es auch bei der 2nd. DSL-Firmware schon immer machbar wäre ?

Etwas Platz kann man noch sparen wenn mann "avme" mit raus nimmt. Bei den Languages ist nicht mehr viel rauszuholen.
Aktuell reicht es nicht mal mehr für "nano, tcpdump, mtr, netcat oder irgend ein anderes kleines Tool/lib".
Auch für zlib ist nicht mal mehr Platz.

**Comment by fda77** [comment]
- Ein PR wär mir vieeeeeeeel lieber!
 - In config/.img/ nichts ändern, das macht die gh-action automatisch.
 - docs/FIRMWARES.md fehlt

> Vorschlag für eine weitere "Removing"-Option, ggfs. auch sinnvoll für die anderen LTE-Modelle (im Labor+Finals):

Ich hab so ein Teil nicht, daher muss das jemand mit machen, da man schauen muss was raus kann und vor allem die webif-änderungen gehen nicht blind
Hast du mal geschaut was da sonst so an grossen dateien drin ist? Evtl sind irgend debug-tools drin die raus könnten (rrdtool, benachmark)

> Wenn im Image nur noch die aktuellere LTE-Firmware enthalten ist, erfolgt automatisch direkt nach dem ersten Flashen dann
einmalig ein Firmware-Update des USB-Moduls, welches auch im Logfile protokolliert wird beim ersten Neustart.

Interessante sache. Nach diesem einmalengen(??) update bräuchte man diese firmware gar nicht mehr im fos?

Und nicht vergessen avm nach sourcen zu fragen

**Comment by fda77** [comment]
Du kannst gern jeden Tag eine neuere Labor Version reinmachen - solang du es selbst macht

Bei Freetz ist das mit den brandings etwas anders, die werden alle in ein "all" Verzeichnis gepackt und verlinkt. AVM hat je ein Verzeichnis. Das war schon bei DS so. Daran spart man also nichts.

Wenn ein Webif-Patch nicht mehr für 7.50 passt sollte jemand den anpassen. Hab ja bereits gesagt dass kein webif patches nicht blind machen kann+will!
Daher wäre meine Lösung: remove dsl firmware für lte geräte deaktivieren

Was man aus /usr/share/lte löschen kann muss man in den avm-scripten nachschauen. Ich hab aktuell aber nicht mehr alls avm-images lokal entpackt, die Platte ist voll. Das macht man eh am besten wenn man so ein Gerät zum ausprobieren hat.
Falls du das nicht selbst machen möchtest: https://github.com/Freetz-NG/freetz-ng/discussions/categories/wishlist (was nicht bedeutet dass es tatsächlich jemand macht)

Die .lua Dateien scheinen mir recht gross

**Comment by fda77** [comment]
Du hattest nur 50% gefunden: https://github.com/Freetz-NG/freetz-ng/commit/72fb52770844bdf4c9cd13ec5aa560712c603fae
