### ISSUE TITLE
fehlende Module in Freetz der F.Ben 6591/6660

### ISSUE THREAD

**Issue by Prisrak1** [Freetz-NG/freetz-ng#78]
kann man evtl. die Einstellungen für den Bau der Freetz 6660/6591 Firmware 7.21 in der "make kernel-menuconfig" bereits richtig einstellen?
```
WARNING: File of kernel module not found: crc16.ko
WARNING: File of kernel module not found: ext3.ko
WARNING: File of kernel module not found: ext4.ko
WARNING: File of kernel module not found: jbd2.ko
WARNING: File of kernel module not found: mbcache.ko
ERROR: Enable missing with 'make kernel-menuconfig' as (M)odule (and push a pull request). Use '/' to search in menuconfig.
Makefile:275: recipe for target 'firmware-nocompile' failed
make: *** [firmware-nocompile] Error 1
```

**Comment by fda77** [comment]
Ist das eine rhetorische Frage? Du hast doch selbst gepostet wie es geht:
make kernel-menuconfig aufrufen und auswählen was du brauchst
mit make kernel-precompiled schauen ob der kernel noch compiliert
einen pull-request erstellen, siehe "Pull request" auf https://freetz-ng.github.io/freetz-ng/SUPPORT.html

**Comment by Prisrak1** [comment]
es freut mich sehr, dass du mitließt. Das immer wieder verändern des Quellcodes nimmt viel Zeit in Anspruch.  Denn auch das ".. FREETZ_STYLE_COLORED in Web Interface.." bei meinem und deinem Skin könnte man auch als grün benutzen. Ist noch nicht gemacht worden. Ich hätte beides gern automatisch vorangestellt gehabt. Das mit dem Pull request klappt bei mir noch nicht.

**Comment by fda77** [comment]
Freut mich noch viel mehr :D
Geht wohl wegen den generischen Fehlerbehebungen an den Modulen

Wie, Skin ist noch nicht gemacht worden? Ich hab extra nochmal nachgeschaut und konnte keinen pull-request finden. Erinnerung: Du hast den Ursprung der Mauszeiger vergessen...

**Comment by Prisrak1** [comment]
pull-request Funktioniert bei mir noch nicht, Dies hat mit der angefragten Skin-Umstellung von grau auf Grün und Grau, bzw. Benutzung dieser zwei verschiedenen Möglichkeiten, nichts zu tun. Die Mauszeiger (erinnere mich immer noch) werden von mir aktualisiert, bzw. neu erstellt.

**Comment by fda77** [comment]
Wenn bei dir grunsätzlich pull-request "nicht geht", wende dich an support@github.com

Du scheinst aber etwas grundlegendes nicht verstanden zu haben
falsch: jemand will was, kommt hier her und schreit "ich will" und sonstwer kümmert sich darum
richtig: wenn du ein Update von deinem Skin willst und dass bei diesem grüne bars erlaubt sind, mach daraus einen pull request.

**Comment by Prisrak1** [comment]
ich bemühe mich, danke für Hinweis.. benötigt "ich will" wird efinitiv nichts.

**Comment by fda77** [comment]
Dann lösch die 1 Zeile die die grünen Bars für dein Skin verhindert
