### ISSUE TITLE
KConfig checksum error

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#9]
There is a checksum error with one of todays changes.

![checksum_kconfig](https://user-images.githubusercontent.com/14336586/70460685-347a7780-1ab7-11ea-9dd5-106ea523cec0.png)

**Comment by fda77** [comment]
Thanks, i've reported it here: https://www.digital-eliteboard.com/threads/fragen-und-probleme-zum-freetz-svn-server.470977/post-3710270
It seems the file is unXZed

**Comment by fda77** [comment]
fixed
