### ISSUE TITLE
curl_ntlm_wb.c (temporary) issue

### ISSUE THREAD

**Issue by Ircama** [Freetz-NG/freetz-ng#938]
FYI, while pulling https://github.com/Freetz-NG/freetz-ng/commit/24330f62056ccfa7911801778998d27cce69298a, I had to edit ./source/target-mips_gcc-13.2.0_uClibc-1.0.45-nptl_kernel-4.9/curl-8.6.0/lib/curl_ntlm_wb.c

changing

```
usigned char buf[1024]
```

to

```
unsigned char buf[1024];
```

Sorry to be generic, but I do not know where this was picked up (perhaps somewhere https://github.com/Freetz-NG/freetz-ng/blob/0e5a4cb43d234f58527477124e06b26fc6987df0/make/pkgs/curl/curl.mk).

Everything else of my compilation worked.

**Comment by fda77** [comment]
Seems to be an upstream problem. Put patches into make/pkgs/curl/patches/ and then "make curl-recompile""
