### ISSUE TITLE
4390/3370 Alien Patch

### ISSUE THREAD

**Issue by Himan2001** [Freetz-NG/freetz-ng#97]
The LED Order/Function is actualy broken when using the 3490-Alien on a 3370 box.

The LAN-LED is off, and the Info LED becomes the "orange" PowerLED at the moment.
The DSL Led i haven´t cheched right now, just first time compiled the image for a 3370 right now.

**Comment by fda77** [comment]
https://github.com/Freetz-NG/freetz-ng/commit/7dcf191b3f6c2f60358fffcbeeb401cc8c27b267
